# Generated by Django 5.2.1 on 2025-07-05 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cajonera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contenedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='simple', max_length=30)),
                ('url', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Formulario_Campos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Formulario_Campos_Contiene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Formulario_Campos_Empieza_Con',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ListaProveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('abreviatura', models.CharField(max_length=5)),
                ('hay_csv_pendiente', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo_Campos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Muro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muro_html', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='NavBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_inicial', models.CharField(max_length=20)),
                ('text_display', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Plantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plantilla_html', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Carpeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sub_Titulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tipo_Cartel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tipo_Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Cajon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=20, null=True)),
                ('cajonera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bdd.cajonera')),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArticuloSinRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=300)),
                ('cantidad', models.FloatField(default=1.0)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulos_sin_registro', to='bdd.carrito')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=20, null=True)),
                ('barras', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('precio_base', models.FloatField(blank=True, default=0.0)),
                ('porcentaje', models.FloatField(blank=True, default=1.0)),
                ('porcentaje_efectivo', models.FloatField(blank=True, default=1.0)),
                ('porcentaje_oferta', models.FloatField(blank=True, default=1.0)),
                ('porcentaje_oferta_efectivo', models.FloatField(blank=True, default=1.0, null=True)),
                ('oferta', models.BooleanField(default=False)),
                ('precio_rollo_caja', models.BooleanField(default=False)),
                ('venta_rollo_caja', models.BooleanField(default=False)),
                ('porcentaje_metro', models.FloatField(blank=True, default=1.0)),
                ('pack_cantidad', models.FloatField(blank=True, default=1.0)),
                ('cantidad_rollo_caja', models.FloatField(blank=True, default=1.0)),
                ('descuento_rollo_caja', models.FloatField(blank=True, default=1.0)),
                ('descuento_rollo_caja_efectivo', models.FloatField(blank=True, default=1.0)),
                ('final_rollo', models.FloatField(blank=True, default=0.0)),
                ('final_rollo_efectivo', models.FloatField(blank=True, default=0.0)),
                ('final', models.FloatField(blank=True, default=0.0)),
                ('final_efectivo', models.FloatField(blank=True, default=0.0)),
                ('trabajado', models.BooleanField(default=False)),
                ('actualizado', models.BooleanField(default=False)),
                ('fecha', models.DateField(auto_now_add=True, null=True)),
                ('stock', models.FloatField(blank=True, default=0.0)),
                ('tiene_cartel', models.BooleanField(default=False)),
                ('p_c_efectivo', models.FloatField(blank=True, default=0.0)),
                ('p_c_debito', models.FloatField(blank=True, default=0.0)),
                ('p_c_credito', models.FloatField(blank=True, default=0.0)),
                ('cajon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bdd.cajon')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bdd.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Cod_Barras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barras', models.IntegerField(blank=True, null=True)),
                ('articulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bdd.item')),
            ],
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(default=1.0)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_efectivo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulos', to='bdd.carrito')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdd.item')),
            ],
        ),
        migrations.CreateModel(
            name='Armador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vista', models.CharField(blank=True, default='Inicio', max_length=30)),
                ('url', models.CharField(blank=True, default='', max_length=30)),
                ('url_nombre', models.CharField(default='', max_length=30)),
                ('modelo', models.CharField(max_length=30)),
                ('busqueda', models.BooleanField(default=False)),
                ('formulario', models.CharField(max_length=30)),
                ('formulario_boton', models.CharField(default='', max_length=30)),
                ('contenedor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bdd.contenedor')),
                ('formulario_campos', models.ManyToManyField(blank=True, null=True, to='bdd.formulario_campos')),
                ('formulario_campos_contiene', models.ManyToManyField(blank=True, null=True, to='bdd.formulario_campos_contiene')),
                ('formulario_campos_empieza_con', models.ManyToManyField(blank=True, null=True, to='bdd.formulario_campos_empieza_con')),
                ('modelo_campos', models.ManyToManyField(to='bdd.modelo_campos')),
                ('muro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdd.muro')),
                ('nav_bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdd.navbar')),
            ],
        ),
        migrations.AddField(
            model_name='contenedor',
            name='a',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='plantilla_a', to='bdd.plantilla'),
        ),
        migrations.AddField(
            model_name='contenedor',
            name='b',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plantilla_b', to='bdd.plantilla'),
        ),
        migrations.AddField(
            model_name='contenedor',
            name='c',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plantilla_c', to='bdd.plantilla'),
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_display', models.CharField(blank=True, max_length=30, null=True)),
                ('cuit', models.CharField(max_length=13)),
                ('direccion', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('corredor', models.CharField(max_length=50)),
                ('corredor_telefono', models.CharField(max_length=50)),
                ('identificador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bdd.listaproveedores')),
            ],
        ),
        migrations.CreateModel(
            name='Listado_Planillas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, null=True)),
                ('descripcion', models.CharField(default='', max_length=50)),
                ('identificador', models.CharField(default='', max_length=50, unique=True)),
                ('hoja', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('listo', models.BooleanField(default=False)),
                ('descargar', models.BooleanField(default=False)),
                ('link_descarga', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('link_descarga_ods', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('id_sp', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('hojas', models.TextField(blank=True, default='', max_length=300, null=True)),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bdd.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Lista_Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(default=0.0)),
                ('pedido', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdd.item')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdd.proveedor')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bdd.proveedor'),
        ),
        migrations.CreateModel(
            name='Condiciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fila_inicial', models.IntegerField(default=1)),
                ('codigo', models.CharField(max_length=1)),
                ('nombre', models.CharField(max_length=1)),
                ('precio_base', models.CharField(max_length=1)),
                ('porcentaje', models.FloatField(default=1.0)),
                ('porcentaje_21', models.FloatField(default=1.0)),
                ('porcentaje_10_5', models.FloatField(default=1.0)),
                ('dolar', models.CharField(max_length=1)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdd.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('numero_remito', models.IntegerField()),
                ('importe', models.FloatField(default=0.0)),
                ('saldo', models.FloatField(default=0.0)),
                ('observaciones', models.TextField()),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdd.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agregado', models.DateField(auto_now_add=True)),
                ('editado', models.DateField(auto_now=True)),
                ('archivo', models.FileField(blank=True, null=True, unique=True, upload_to='inbox')),
                ('condiciones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdd.condiciones')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdd.proveedor')),
            ],
        ),
        migrations.AddField(
            model_name='cajonera',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bdd.sector'),
        ),
        migrations.AddField(
            model_name='item',
            name='sub_carpeta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bdd.sub_carpeta'),
        ),
        migrations.AddField(
            model_name='item',
            name='sub_titulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bdd.sub_titulo'),
        ),
        migrations.AddField(
            model_name='item',
            name='tipo_cartel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bdd.tipo_cartel'),
        ),
        migrations.CreateModel(
            name='Registros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('nombre', models.CharField(default='', max_length=30)),
                ('link', models.CharField(default='', max_length=200)),
                ('link_descargar', models.CharField(default='', max_length=200)),
                ('automatioco', models.BooleanField(default=False)),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bdd.tipo_registro')),
            ],
        ),
    ]
