# Generated by Django 4.0.6 on 2026-05-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='factor_division',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
