# Generated by Django 4.0.6 on 2026-05-06 15:04

from django.db import migrations, models


def backfill_base(apps, schema_editor):
    """Copia los valores actuales de final/final_efectivo/final_rollo/
    final_rollo_efectivo a sus respectivos *_base. Asume que ningún item
    tiene factor_division aplicado a esos valores (estado pre-feature).
    """
    Item = apps.get_model('bdd', 'Item')
    Item.objects.update(
        final_base=models.F('final'),
        final_efectivo_base=models.F('final_efectivo'),
        final_rollo_base=models.F('final_rollo'),
        final_rollo_efectivo_base=models.F('final_rollo_efectivo'),
    )


def reverse_backfill(apps, schema_editor):
    # No hay nada que revertir explícitamente; los campos *_base se eliminan
    # cuando se revierte la AddField. Esta función queda como noop.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('bdd', '0002_item_factor_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='final_base',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='item',
            name='final_efectivo_base',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='item',
            name='final_rollo_base',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='item',
            name='final_rollo_efectivo_base',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.RunPython(backfill_base, reverse_backfill),
    ]
