# Generated by Django 4.0.6 on 2026-07-12 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bdd', '0003_item_final_base_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='listado_planillas',
            name='descargado',
            field=models.BooleanField(default=False, help_text='Indica si la planilla fue descargada por el usuario'),
        ),
        migrations.AddField(
            model_name='listado_planillas',
            name='fecha_descarga',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que se descargó la planilla', null=True),
        ),
        migrations.AddField(
            model_name='listado_planillas',
            name='usuario_descarga',
            field=models.ForeignKey(blank=True, help_text='Usuario que descargó la planilla', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planillas_descargadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
