# Generated by Django 4.0.6 on 2026-08-06 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdd', '0004_listado_planillas_descargado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listado_planillas',
            name='error_columnas',
            field=models.CharField(blank=True, default='', help_text='Columnas vacias detectadas (Codigo, Descripcion, Publico)', max_length=200, null=True),
        ),
    ]
