# Generated by Django 5.2.1 on 2025-07-05 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cartel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('constante', models.FloatField(default=0.0)),
                ('abreviatura', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.CharField(max_length=200)),
                ('trabajado', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='articulos.categoria')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='articulos.marca')),
            ],
        ),
        migrations.CreateModel(
            name='CodigoBarras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barras', models.CharField(max_length=200, unique=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulos.articulo')),
            ],
        ),
        migrations.CreateModel(
            name='ArticuloProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_base', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=200)),
                ('precio_base', models.FloatField(default=0.0)),
                ('actualizado', models.BooleanField(default=True)),
                ('fecha', models.DateField(auto_now_add=True, null=True)),
                ('codigo_final', models.CharField(max_length=20)),
                ('precio_final', models.FloatField(blank=True, default=0.0)),
                ('precio_contado', models.FloatField(blank=True, default=0.0)),
                ('precio_cantidad', models.FloatField(blank=True, default=0.0)),
                ('precio_cantidad_contado', models.FloatField(blank=True, default=0.0)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulos.articulo')),
                ('cartel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='articulos.cartel')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulos.proveedor')),
            ],
        ),
    ]
