[pytest]
python_files = test_*.py
testpaths = tests
addopts = -v --tb=short --cov=core_testing --cov-report=term-missing

[coverage:run]
source = core_testing
omit = 
    */migrations/*
    */tests/*
    */__init__.py

[coverage:report]
exclude_lines =
    # Have to re-enable the standard pragma
    pragma: no cover
    # Don't complain about missing debug-only code:
    def __repr__
    if self\.debug
    raise NotImplementedError
    # Don't complain if tests don't hit defensive assertion code:
    raise AssertionError
    raise NotImplementedError
    # Don't complain if non-runnable code isn't run:
    if 0:
    if __name__ == .__main__.:
    @abc.abstractmethod
    def _abstract
