# Generated by Django 5.2.1 on 2025-07-05 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bdd', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CierreZ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('RESERVADO_SIEMPRE_CERO', models.IntegerField(default=0)),
                ('cant_doc_fiscales', models.IntegerField(default=0)),
                ('cant_doc_fiscales_a_emitidos', models.IntegerField(default=0)),
                ('cant_doc_fiscales_bc_emitidos', models.IntegerField(default=0)),
                ('cant_doc_fiscales_cancelados', models.IntegerField(default=0)),
                ('cant_doc_nofiscales', models.IntegerField(default=1)),
                ('cant_doc_nofiscales_homologados', models.IntegerField(default=0)),
                ('cant_nc_a_fiscales_a_emitidos', models.IntegerField(default=0)),
                ('cant_nc_bc_emitidos', models.IntegerField(default=0)),
                ('cant_nc_canceladas', models.IntegerField(default=0)),
                ('monto_credito_nc', models.FloatField(default=0.0)),
                ('monto_imp_internos', models.FloatField(default=0.0)),
                ('monto_imp_internos_nc', models.FloatField(default=0.0)),
                ('monto_iva_doc_fiscal', models.FloatField(default=0.0)),
                ('monto_iva_nc', models.FloatField(default=0.0)),
                ('monto_iva_no_inscripto', models.FloatField(default=0.0)),
                ('monto_iva_no_inscripto_nc', models.FloatField(default=0.0)),
                ('monto_percepciones', models.FloatField(default=0.0)),
                ('monto_percepciones_nc', models.FloatField(default=0.0)),
                ('monto_ventas_doc_fiscal', models.FloatField(default=0.0)),
                ('status_fiscal', models.CharField(default='0600', max_length=4)),
                ('status_impresora', models.CharField(default='C080', max_length=4)),
                ('ultima_nc_a', models.IntegerField(default=30)),
                ('ultima_nc_b', models.IntegerField(default=327)),
                ('ultimo_doc_a', models.IntegerField(default=2262)),
                ('ultimo_doc_b', models.IntegerField(default=66733)),
                ('ultimo_remito', models.IntegerField(default=0)),
                ('zeta_numero', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=45)),
                ('cuit_dni', models.CharField(max_length=11)),
                ('responsabilidad_iva', models.CharField(choices=[('I', 'Responsable inscripto'), ('E', 'Exento'), ('A', 'No responsable'), ('C', 'Consumidor final'), ('B', 'Responsable no inscripto, venta de bienes de uso'), ('M', 'Resp. monotributo'), ('S', 'Monotributista social'), ('V', 'Pequeño contribuyente eventual'), ('W', 'Pequeño contribuyente eventual social'), ('T', 'No categorizado')], default='C', max_length=1)),
                ('tipo_documento', models.CharField(choices=[('C', 'CUIT'), ('0', 'Libreta de enrolamiento'), ('1', 'Libreta cívica'), ('2', 'Documento Nacional de Identidad'), ('3', 'Pasaporte'), ('4', 'Cédula de identidad'), (' ', 'Sin calificador')], default=' ', max_length=1)),
                ('domicilio', models.CharField(blank=True, max_length=45, null=True)),
                ('telefono', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.CharField(max_length=250)),
                ('ticket', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ArticuloVendido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField()),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bdd.item')),
                ('sin_registrar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bdd.articulosinregistro')),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total', models.FloatField(default=0.0)),
                ('tipo_cbte', models.CharField(default='', max_length=3)),
                ('numero_cbte', models.IntegerField(default=0)),
                ('articulos_vendidos', models.ManyToManyField(to='facturacion.articulovendido')),
                ('cliente', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='facturacion.cliente')),
                ('metodo_de_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.metodopago')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
