# Generated by Django 4.0.6 on 2026-03-17 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bdd', '0001_initial'),
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulovendido',
            name='descripcion_sin_registro',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='articulovendido',
            name='is_sin_registro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='articulovendido',
            name='precio_unitario_al_vender',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='articulovendido',
            name='sin_registrar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bdd.articulosinregistro'),
        ),
    ]
