# Generated by Django 4.0.6 on 2026-03-26 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bdd', '0001_initial'),
        ('facturacion', '0002_articulovendido_descripcion_sin_registro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulovendido',
            name='descripcion_sin_registro',
        ),
        migrations.RemoveField(
            model_name='articulovendido',
            name='is_sin_registro',
        ),
        migrations.RemoveField(
            model_name='articulovendido',
            name='precio_unitario_al_vender',
        ),
        migrations.AlterField(
            model_name='articulovendido',
            name='sin_registrar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bdd.articulosinregistro'),
        ),
    ]
