# Generated by Django 5.2.1 on 2025-07-05 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=250)),
                ('precio_base', models.FloatField(default=0.0)),
                ('ultimo_cambio', models.DateField(auto_now_add=True, null=True)),
                ('actualizado', models.BooleanField(default=False)),
                ('precio_efectivo', models.FloatField(default=0.0)),
            ],
        ),
    ]
