# -*- coding: utf-8 -*-
"""Procesador de informes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pf-Fqu9cufGgoEtyJoMxx1qthZtxrgkj

# Funciones

## Inicio
"""

!pip install odfpy
!pip install xlwt

import os
import pandas as pd
import numpy as np

RUTA_RAIZ = '/content/drive/MyDrive/Proveedores en automatico/Contaduria y Control/Informes Ferreteria/'
CARPETA_PLANILLAS = 'Planillas diarias/'
CARPETA_INFORMES = 'Informes Finales/'

ANIOS = [
    #'2024/',
    #'2025/',
    '2026/',
]

"""## Funciones Utils"""

def leer_todas_hojas(filename):
    if not os.path.isfile(filename):
        return None

    xls = pd.ExcelFile(filename)
    sheets = xls.sheet_names

    results = {}

    for sheet in sheets:
        results[sheet] = xls.parse(sheet)

    xls.close()

    return results, sheets

# -*- coding: utf-8 -*-

# 1. Instalar la biblioteca necesaria (si no está ya instalada)
#    Descomenta la siguiente línea si es la primera vez que usas gspread en este notebook
# !pip install gspread pandas

# 2. Importar las bibliotecas necesarias
import gspread
import pandas as pd
from google.colab import auth
import google.auth
from google.auth.exceptions import RefreshError
from gspread.exceptions import SpreadsheetNotFound, APIError

# 3. Autenticar al usuario en Google Colab
#    Esto abrirá una ventana emergente para que inicies sesión y concedas permisos.
try:
    auth.authenticate_user()
    print("Autenticación exitosa.")
except Exception as e:
    print(f"Error durante la autenticación: {e}")
    # Puedes decidir si quieres detener la ejecución o manejar el error de otra forma
    raise # Detiene la ejecución si la autenticación falla

# 4. Autorizar a gspread para usar las credenciales obtenidas
try:
    creds, _ = google.auth.default()
    gc = gspread.authorize(creds)
    print("Autorización de gspread exitosa.")
except RefreshError as e:
    print(f"Error al autorizar gspread (problema con credenciales): {e}")
    print("Intenta re-autenticar ejecutando la celda de 'auth.authenticate_user()' de nuevo.")
    raise
except Exception as e:
    print(f"Error inesperado al autorizar gspread: {e}")
    raise

# 5. Definir la función para leer el Google Sheet por ID
def leer_google_sheet_por_id(spreadsheet_id):
    """
    Lee todas las hojas de un Google Sheet específico usando su ID.

    Args:
        spreadsheet_id (str): El ID del Google Sheet. Este ID se encuentra
                              en la URL del sheet, entre '/d/' y '/edit'.
                              Ej: https://docs.google.com/spreadsheets/d/ESTE_ES_EL_ID/edit

    Returns:
        tuple: Una tupla conteniendo:
            - dict: Un diccionario donde las claves son los nombres de las hojas
                    y los valores son DataFrames de pandas con los datos de cada hoja.
            - list: Una lista con los nombres de todas las hojas.
        Retorna (None, None) si ocurre un error al acceder al Sheet
        (ej. ID incorrecto, falta de permisos).
    """
    results = {}
    sheet_names = []

    try:
        # Abre el Google Sheet usando su ID (key)
        # Asegúrate de que la cuenta con la que te autenticaste tiene acceso (al menos lectura) a este Sheet.
        spreadsheet = gc.open_by_key(spreadsheet_id)
        #print(f"Accediendo al Google Sheet: '{spreadsheet.title}'")

        # Obtiene todas las hojas (worksheets) dentro del spreadsheet
        worksheets = spreadsheet.worksheets()

        # Itera sobre cada hoja
        for ws in worksheets:
            sheet_name = ws.title
            sheet_names.append(sheet_name)
            #print(f"  Leyendo hoja: '{sheet_name}'...")

            # Obtiene todos los valores de la hoja actual como una lista de listas
            data = ws.get_all_values()

            # Convierte los datos a un DataFrame de Pandas
            # Asume que la primera fila es el encabezado. Si no es así, ajusta la lógica.
            if data:
                # Si hay datos, usa la primera fila como cabecera y el resto como datos
                df = pd.DataFrame(data[1:], columns=data[0])
            else:
                # Si la hoja está vacía, crea un DataFrame vacío
                df = pd.DataFrame()

            results[sheet_name] = df
            #print(f"  Hoja '{sheet_name}' leída, {len(df)} filas encontradas.")

        print("Todas las hojas han sido leídas exitosamente.")
        return results, sheet_names

    except SpreadsheetNotFound:
        #print(f"Error: No se encontró el Google Sheet con ID '{spreadsheet_id}'.")
        #print("Verifica que el ID sea correcto y que la cuenta con la que te autenticaste tenga permiso de acceso.")
        return None, None
    except APIError as e:
        # Esto puede ocurrir por varias razones, incluyendo permisos insuficientes
        #print(f"Error de API al acceder al Google Sheet (ID: {spreadsheet_id}): {e}")
        #print("Verifica los permisos de la cuenta y que la API de Google Sheets esté habilitada si es necesario (generalmente no lo es para lectura básica en Colab).")
        return None, None
    except Exception as e:
        # Captura cualquier otro error inesperado
        #print(f"Ocurrió un error inesperado al procesar el Sheet (ID: {spreadsheet_id}): {e}")
        return None, None

def modificar_primer_gasto(archivo, hoja):
    df = pd.read_excel(archivo, sheet_name=hoja, header=None)
    for fila in range(min(40, len(df))):  # Verificar solo las primeras 40 filas
        for columna in range(len(df.columns)):
            if df.iloc[fila, columna] == 'GASTOS':
                df.iloc[fila, columna] = 'TABLA GASTOS'
                return df  # Detener después de modificar la primera aparición
    return df



# --- FUNCIÓN 1: Renombrar Valores Específicos ---
# Esta función toma un DataFrame y aplica los reemplazos de texto específicos
# que estaban dentro del bucle original.

def renombrar_valores_especificos(df_entrada):
    """
    Busca y reemplaza valores de texto específicos dentro de un DataFrame.

    Args:
        df_entrada (pd.DataFrame): El DataFrame a modificar.

    Returns:
        pd.DataFrame: El DataFrame con los valores reemplazados.
                      Retorna una copia para no modificar el original inesperadamente.
    """
    df = df_entrada.copy() # Trabajar sobre una copia

    # Mapeo de valores a buscar y sus reemplazos
    reemplazos = {
        'TOTAL TARJ. CREDITO': 'TOTAL TARJ. CRED',
        'total dni': 'TOTAL DNI',
        'TOTAL DURACRIL': 'TOTAL DNI', # Nota: también reemplaza a 'TOTAL DNI'
        'TOTAL MASTRO DEBITO': 'TOTAL MASTRO D'
    }

    print("--- Iniciando renombrado específico ---")
    for valor_buscar, valor_reemplazar in reemplazos.items():
        try:
            # np.where devuelve tuplas de arrays (uno por dimensión)
            filas, columnas = np.where(df.values == valor_buscar)

            if len(filas) > 0:
                # Iterar por si aparece más de una vez (aunque el código original solo usaba la primera)
                for fila, columna in zip(filas, columnas):
                     # Verificar si la celda aún contiene el valor original (por si acaso)
                     if df.iloc[fila, columna] == valor_buscar:
                         print(f"  Encontrado '{valor_buscar}' en ({fila}, {columna}). Reemplazando por: '{valor_reemplazar}'")
                         df.iloc[fila, columna] = valor_reemplazar
            # else:
            #     print(f"  Valor '{valor_buscar}' no encontrado.") # Descomentar para depurar

        except Exception as e:
            # Captura errores más específicos si es necesario, pero evita el 'pass' silencioso.
            print(f"  Advertencia: Ocurrió un error buscando/reemplazando '{valor_buscar}': {e}")
            # Considera si deberías detener el proceso o solo registrar el error.
            # Por ahora, continuamos como en el original.
            pass
    print("--- Fin renombrado específico ---")
    return df


# --- FUNCIÓN 2: Buscar Valores Adyacentes a Encabezados ---
# Esta función toma un DataFrame (ya procesado/renombrado) y busca los valores
# asociados a una lista de encabezados, aplicando la lógica de buscar en la
# columna adyacente (+1 o +2 según el caso).

def buscar_valores_finales_parametrizado(df, encabezados_a_buscar, config_desplazamientos, default_config):
    """
    Busca valores en columnas adyacentes a etiquetas específicas en un DataFrame,
    utilizando una configuración parametrizada para el desplazamiento y manejo de NaN.

    Args:
        df (pd.DataFrame): El DataFrame donde buscar.
        encabezados_a_buscar (list): Lista de strings con los encabezados a buscar.
        config_desplazamientos (list): Una lista de diccionarios. Cada diccionario
                                       define un grupo de encabezados y su comportamiento:
                                       {'nombres': ['Lista', 'De', 'Encabezados'],
                                        'offset': int,  # Desplazamiento de columna
                                        'nan_a_cero': bool # Si True, convierte NaN a 0
                                       }
        default_config (dict): Un diccionario con la configuración por defecto
                               a usar si un encabezado no está en ningún grupo:
                               {'offset': int, 'nan_a_cero': bool}

    Returns:
        dict: Diccionario {encabezado: valor_encontrado}.
    """
    resultados_finales = {}
    print(f"\n--- Buscando valores (parametrizado) para: {encabezados_a_buscar} ---")

    for encabezado in encabezados_a_buscar:
        valor_encontrado = None
        try:
            # Buscar la primera ocurrencia del encabezado
            filas, columnas = np.where(df.values == encabezado)

            if len(filas) > 0:
                fila = filas[0]
                columna = columnas[0]
                print(f"  Encabezado '{encabezado}' encontrado en ({fila}, {columna}).")

                # --- Determinar configuración para ESTE encabezado ---
                offset_actual = default_config['offset']
                convertir_nan = default_config['nan_a_cero']
                config_usada = "por defecto"

                for grupo in config_desplazamientos:
                    if encabezado in grupo.get('nombres', []): # Usar .get para seguridad
                        offset_actual = grupo.get('offset', default_config['offset']) # Usar default si falta
                        convertir_nan = grupo.get('nan_a_cero', default_config['nan_a_cero']) # Usar default si falta
                        config_usada = f"grupo {grupo.get('nombres')}"
                        print(f"    Usando configuración específica ({config_usada}): offset={offset_actual}, nan_a_cero={convertir_nan}")
                        break # Encontró config específica, salir del bucle de grupos

                if config_usada == "por defecto":
                     print(f"    Usando configuración por defecto: offset={offset_actual}, nan_a_cero={convertir_nan}")
                # --- Fin determinación de configuración ---

                columna_valor = columna + offset_actual

                # Verificar si la columna calculada existe
                if columna_valor < df.shape[1]:
                    print(f"    Buscando valor en columna {columna_valor} (offset {offset_actual}).")
                    valor_celda = df.iloc[fila, columna_valor]

                    # Aplicar conversión de NaN si corresponde
                    if convertir_nan and pd.isna(valor_celda):
                        print(f"    Valor en ({fila}, {columna_valor}) es NaN/NaT y nan_a_cero=True. Asignando 0.")
                        valor_encontrado = 0
                    else:
                        # Si no es NaN o no hay que convertir, tomar el valor como está
                        valor_encontrado = valor_celda
                else:
                    # La columna calculada no existe
                    print(f"    Advertencia: No existe la columna {columna_valor} (col={columna} + offset={offset_actual}).")
                    valor_encontrado = None # O podrías querer asignar 0 u otro valor

            else:
                # No se encontró el encabezado en el DataFrame
                print(f"  Encabezado '{encabezado}' no encontrado en el DataFrame.")
                valor_encontrado = None # Ya es None por defecto, pero explícito

        except Exception as e:
            print(f"  Error procesando el encabezado '{encabezado}': {e}")
            # Considera logging o un manejo más específico del error
            valor_encontrado = None # Asegurar None en caso de error inesperado

        finally:
            # Guardar el resultado para este encabezado
            resultados_finales[encabezado] = valor_encontrado
            print(f"    -> Resultado para '{encabezado}': {valor_encontrado}")

    print("--- Fin búsqueda de valores (parametrizado) ---")
    return resultados_finales



def buscar_valores(archivo, hojas, encabezados_ods, config_desplazamientos, default_config):
    """
    Función envoltorio que procesa varias hojas de un archivo, aplicando
    modificaciones, renombrados y búsqueda de valores parametrizada.

    Args:
        archivo (str): Ruta al archivo Excel.
        hojas (list): Lista de nombres de hojas a procesar.
        encabezados_ods (list): Lista de encabezados cuyos valores se buscan.
        config_desplazamientos (list): Configuración para buscar_valores_finales_parametrizado.
        default_config (dict): Configuración por defecto para buscar_valores_finales_parametrizado.

    Returns:
        dict: Diccionario con los resultados {nombre_hoja: {encabezado: valor}}.
    """
    resultados = {}
    print(f"\n<<<<<<< Iniciando Proceso General para Archivo: {archivo} >>>>>>>")
    for hoja in hojas:
        print(f"\n======= Procesando Hoja: {hoja} =======")
        try:
            # Paso 1: Modificar primer 'GASTOS' (o simplemente leer si ya no es necesario)
            df_modificado_primer_gasto = modificar_primer_gasto(archivo, hoja)

            # Paso 2: Renombrar valores específicos ('TOTAL TARJ. CREDITO', etc.)
            df_renombrado = renombrar_valores_especificos(df_modificado_primer_gasto)

            # Paso 3: Buscar valores finales usando la configuración parametrizada
            resultados[hoja] = buscar_valores_finales_parametrizado(
                df_renombrado,
                encabezados_ods,
                config_desplazamientos, # Pasar la configuración
                default_config         # Pasar el default
            )
        except FileNotFoundError:
             print(f"  ERROR: Archivo '{archivo}' no encontrado.")
             # Podrías retornar un diccionario vacío o lanzar la excepción
             return {"Error": f"Archivo no encontrado: {archivo}"}
        except Exception as e:
            print(f"  ERROR inesperado procesando la hoja '{hoja}': {e}")
            # Guardar indicación del error para esta hoja
            resultados[hoja] = {"Error": f"Error procesando hoja: {e}"}
            # Considera si quieres continuar con otras hojas o detenerte

    print("\n<<<<<<< Fin Proceso General >>>>>>>")
    return resultados



def buscar_monto_gastos_personales(datos_por_hoja, texto_buscar="Total Gastos Personal=", offset_columnas=5):
    """
    Busca un texto específico en cada DataFrame (hoja) y extrae el valor
    de una celda ubicada a un número determinado de columnas a la derecha.

    Args:
        datos_por_hoja (dict): Diccionario {nombre_hoja: pd.DataFrame}.
        texto_buscar (str): El texto exacto a buscar en las celdas.
        offset_columnas (int): Número de columnas a la derecha para extraer el valor.

    Returns:
        tuple: Una tupla conteniendo:
            - dict: Resultados {nombre_hoja: monto_extraido (float) o None}.
            - float: Suma total de los montos encontrados y válidos.
    """
    resultados_informe = {}
    total_general = 0.0
    print(f"\n<<<<<<< Iniciando Búsqueda de '{texto_buscar}' con offset {offset_columnas} >>>>>>>")

    if not datos_por_hoja:
        print("  ADVERTENCIA: No hay datos por hoja para procesar.")
        return {}, 0.0

    # Iteramos sobre cada hoja (DataFrame) en el diccionario
    for nombre_hoja, df in datos_por_hoja.items():
        print(f"\n======= Procesando Hoja: {nombre_hoja} =======")
        monto_encontrado = None # Reseteamos para cada hoja

        if df.empty:
            print("  INFO: La hoja está vacía. Omitiendo.")
            resultados_informe[nombre_hoja] = None
            continue

        try:
            # Convertimos el DataFrame a un array de NumPy (más rápido para buscar)
            # Usamos dtype=str para asegurar que la comparación funcione aunque haya números
            array_datos = df.to_numpy(dtype=str)

            # Buscamos las coordenadas (fila, columna) donde está el texto
            # np.where devuelve una tupla de arrays (uno para filas, uno para columnas)
            coordenadas = np.where(array_datos == texto_buscar)

            if coordenadas[0].size > 0:
                # Si se encontró el texto (tomamos la primera ocurrencia si hay varias)
                fila_idx = coordenadas[0][0]
                col_idx = coordenadas[1][0]
                print(f"  INFO: Texto '{texto_buscar}' encontrado en fila {fila_idx}, columna {col_idx}.")

                # Calculamos el índice de la columna objetivo
                col_objetivo_idx = col_idx + offset_columnas

                # Verificamos si la columna objetivo está dentro de los límites del DataFrame
                if col_objetivo_idx < array_datos.shape[1]:
                    valor_str = array_datos[fila_idx, col_objetivo_idx]
                    print(f"  INFO: Valor en la celda +{offset_columnas} columnas: '{valor_str}'")

                    # --- INICIO BLOQUE MODIFICADO ---
                    try:
                        # 1. Convertir a string y quitar espacios externos
                        valor_procesar = str(valor_str).strip()

                        if valor_procesar: # Solo procesar si no está vacío
                            # 2. Quitar símbolo de moneda (añadir otros si es necesario)
                            valor_procesar = valor_procesar.replace('$', '')
                            # 3. Quitar separador de miles (asumimos que es '.')
                            valor_procesar = valor_procesar.replace('.', '')
                            # 4. Reemplazar separador decimal (asumimos que es ',') por '.'
                            valor_procesar = valor_procesar.replace(',', '.')
                            # 5. Quitar espacios internos restantes
                            valor_procesar = valor_procesar.replace(' ', '')

                            # 6. Intentar conversión a float (si queda algo después de limpiar)
                            if valor_procesar:
                                valor_numerico = float(valor_procesar)
                                monto_encontrado = valor_numerico
                                total_general += monto_encontrado
                                # Mostrar el valor original para claridad
                                print(f"  ÉXITO: Monto numérico extraído: {valor_numerico} (desde '{valor_str}')")
                            else:
                                print(f"  ADVERTENCIA: El valor original '{valor_str}' quedó vacío después de la limpieza.")
                                monto_encontrado = None # Asegurar que es None si queda vacío
                        else:
                            print(f"  ADVERTENCIA: La celda objetivo ('{valor_str}') está vacía o solo contiene espacios.")
                            monto_encontrado = None # Asegurar que es None si estaba vacío

                    except (ValueError, TypeError) as e:
                        # Informar del error específico y el valor problemático
                        print(f"  ADVERTENCIA: El valor '{valor_str}' (procesado como '{valor_procesar}') no pudo ser convertido a número. Error: {e}. Se omitirá del total.")
                        monto_encontrado = None # Asegurar que es None en caso de error
                    # --- FIN BLOQUE MODIFICADO ---

                else:
                    print(f"  ADVERTENCIA: Se encontró '{texto_buscar}', pero no existen {offset_columnas} columnas a la derecha.")
                    monto_encontrado = None
            else:
                print(f"  INFO: Texto '{texto_buscar}' no encontrado en esta hoja.")

        except Exception as e:
            print(f"  ERROR inesperado procesando la hoja '{nombre_hoja}': {e}")
            # Puedes decidir si quieres que el error pare el proceso o solo lo registre

        # Guardamos el resultado para esta hoja (sea el monto o None)
        resultados_informe[nombre_hoja] = monto_encontrado

    print("\n<<<<<<< Fin Búsqueda >>>>>>>")
    return resultados_informe, total_general
import calendar # Para obtener nombres de meses
import locale   # Para intentar obtener nombres de meses en español

# --- Helper Function para extraer el mes ---
def get_month_from_sheet_name(name):
    """
    Intenta extraer el número de mes (1-12) de un string como 'd/m' o 'dd/mm'.
    Ignora mayúsculas/minúsculas y espacios extra. Retorna None si no es válido.
    """
    if isinstance(name, str) and '/' in name:
        parts = name.split('/')
        if len(parts) == 2:
            try:
                # Limpiar día y mes de espacios y tomar la parte del mes (la segunda)
                day_str, month_str = parts[0].strip(), parts[1].strip()
                if day_str and month_str: # Asegurar que ambas partes no estén vacías
                    month = int(month_str)
                    if 1 <= month <= 12:
                        return month # Retorna el número de mes si es válido
            except ValueError:
                # Ocurre si la parte del mes no es un número entero
                pass
            except Exception:
                # Captura cualquier otro error inesperado durante el parseo
                pass
    # Si no tiene formato d/m, o el mes es inválido, o hubo error
    return None

# --- Función Principal Modificada ---
def generar_informe_gastos_con_totales_mensuales(resultados_informe, nombre_archivo="informe_gastos_mensual.xlsx"):
    """
    Genera un archivo Excel con el detalle de gastos por fecha (hoja)
    y añade filas con los totales para cada mes identificado.

    Args:
        resultados_informe (dict): Diccionario {nombre_hoja: monto o None}.
        nombre_archivo (str): Nombre del archivo Excel a generar.
    """
    print(f"\n--- Generando Informe con Totales Mensuales: {nombre_archivo} ---")
    if not resultados_informe:
        print("  ADVERTENCIA: No hay resultados para generar el informe.")
        return # Salir si no hay datos

    # --- 1. Procesar datos originales y calcular totales por mes ---
    datos_para_df_original = []
    totales_por_mes = {} # Diccionario para acumular {mes_numero: total_monto}
    hojas_sin_mes_con_monto = [] # Para registrar hojas no parseables que sí tenían monto

    for nombre_hoja, monto in resultados_informe.items():
        # Siempre añadir la fila original al listado para el DataFrame principal
        datos_para_df_original.append({'Fecha': nombre_hoja, 'Monto': monto})

        # Intentar extraer el mes de la hoja
        mes = get_month_from_sheet_name(nombre_hoja)

        if mes is not None:
            # Si se extrajo un mes válido, intentar sumar el monto
            if monto is not None:
                try:
                    # Asegurarse de que el monto sea numérico antes de sumar
                    monto_float = float(monto)
                    totales_por_mes[mes] = totales_por_mes.get(mes, 0.0) + monto_float
                except (ValueError, TypeError):
                    # Si el monto existe pero no es numérico, registrar advertencia
                    print(f"  ADVERTENCIA: Monto '{monto}' para hoja '{nombre_hoja}' (Mes {mes}) no es numérico, no se incluirá en el total mensual.")
            # else: Si el monto es None, simplemente no se suma a ningún total.
        else:
            # Si no se pudo extraer un mes válido, verificar si había un monto
            if monto is not None:
                # Registrar hoja inválida que sí tenía monto (no se sumará a ningún mes)
                hojas_sin_mes_con_monto.append(nombre_hoja)

    # Informar sobre hojas con montos que no pudieron ser asignadas a un mes
    if hojas_sin_mes_con_monto:
        print(f"  ADVERTENCIA: Las siguientes hojas tienen montos pero no un formato de fecha (d/m) reconocible y sus valores NO se incluirán en los totales mensuales: {hojas_sin_mes_con_monto}")

    # --- 2. Crear DataFrame con los datos originales detallados ---
    df_informe_detalle = pd.DataFrame(datos_para_df_original)
    # Podrías ordenar df_informe_detalle aquí si lo deseas, por ejemplo por 'Fecha'
    # df_informe_detalle = df_informe_detalle.sort_values(by='Fecha') # Orden alfabético simple

    # --- 3. Crear DataFrame para las filas de totales mensuales ---
    datos_para_df_totales = []

    # Intentar obtener nombres de meses en español (puede requerir configuración de locale)
    try:
        # Necesitas tener el locale 'es_ES.UTF-8' instalado en tu sistema/entorno Colab
        locale.setlocale(locale.LC_TIME, 'es_ES.UTF-8')
        month_names_es = {i: calendar.month_name[i].capitalize() for i in range(1, 13)}
    except locale.Error:
        print("\n  ADVERTENCIA: No se pudo establecer el locale 'es_ES.UTF-8'. Usando nombres de meses en inglés.")
        # Fallback a nombres en inglés si el locale español no está disponible
        month_names_es = {i: calendar.month_name[i].capitalize() for i in range(1, 13)}
    except Exception as e:
         print(f"\n  ADVERTENCIA: Error inesperado al obtener nombres de meses ({e}). Usando números de mes.")
         month_names_es = {} # Usará "Mes X"

    # Crear las filas de total, ordenadas por número de mes
    for mes_num in sorted(totales_por_mes.keys()):
        total_mes = totales_por_mes[mes_num]
        # Usar nombre del mes si está disponible, si no, usar "Mes X"
        nombre_mes_str = month_names_es.get(mes_num, f"Mes {mes_num}")
        datos_para_df_totales.append({'Fecha': f'Total {nombre_mes_str}', 'Monto': total_mes})

    df_totales_mes = pd.DataFrame(datos_para_df_totales)

    # --- 4. Combinar los DataFrames (detalle primero, luego totales) ---
    df_final = pd.concat([df_informe_detalle, df_totales_mes], ignore_index=True)

    # --- 5. Exportar el DataFrame combinado a Excel ---
    try:
        df_final.to_excel(nombre_archivo, index=False, sheet_name='InformeGastosMensual')
        print(f"  ÉXITO: Informe guardado correctamente en '{nombre_archivo}'")

        # --- Opcional: Descarga en Colab ---
        # try:
        #     from google.colab import files
        #     files.download(nombre_archivo)
        #     print(f"  INFO: Iniciando descarga de '{nombre_archivo}' (solo en Google Colab).")
        # except ImportError:
        #     print(f"  INFO: Puedes encontrar el archivo '{nombre_archivo}' en el directorio actual.")
        # --- Fin Opcional ---

    except Exception as e:
        print(f"  ERROR: No se pudo guardar el archivo Excel '{nombre_archivo}'.")
        print(f"  Detalle del error: {e}")

def ejecutar_por_archivo(ruta_archivo, ruta_salida):
    results,sheets = leer_todas_hojas(ruta_archivo)
    results[sheets[0]]

    hojas = sheets
    encabezados_ods = ['Z', 'N', 'DIFERENCIA', 'VENTA FINAL', 'TOTAL TARJ. CRED', 'TOTAL VISA DEB', 'TOTAL MASTRO D', 'TOTAL MERCADO', 'TOTAL DNI', 'GASTOS']
    encabezados_xls = ['Días', 'B', 'N', 'D', '', 'TOTAL DIARIO', 'Tarjeta D', 'Tarjeta C', 'Total MP', 'Total DNI', '% Tarjeta D', '% Tarjeta C', '% MP', '% DNI', 'GASTOS']

    # --- Definición de la Configuración (¡Aquí parametrizas!) ---
    config_parametrizada = [
        {
            'nombres': ['TOTAL TARJ. CRED', 'TOTAL MERCADO', 'TOTAL DNI'], # Encabezados de este grupo
            'offset': 2,                                                  # Desplazamiento para este grupo
            'nan_a_cero': True                                            # Convertir NaN a 0 para este grupo
        },
    ]

    # Configuración por defecto para cualquier encabezado NO listado en config_parametrizada
    config_default = {
        'offset': 1,        # Desplazamiento por defecto
        'nan_a_cero': False # Por defecto, no convertir NaN a 0
    }

    resultados = buscar_valores(ruta_archivo, hojas, encabezados_ods, config_parametrizada, config_default)
    resultados_df = pd.DataFrame(resultados).T

    g_df = list()
    for gastos in resultados_df['GASTOS']:
        if gastos:
            print(gastos)
            pass
        else:
            gastos = 0
        g_df.append(gastos)


    resultados_df['GASTOS'] = g_df
    resultados_df.index = resultados_df.index.astype('str')
    resultados_df = resultados_df[resultados_df.index.str.contains('-')]
    resultados_df = resultados_df.fillna(0)

    resultados_df['B'] = resultados_df['Z']
    resultados_df['D'] = resultados_df['DIFERENCIA']
    resultados_df['TOTAL DIARIO'] = resultados_df['VENTA FINAL']
    resultados_df[''] = ''
    resultados_df['Tarjeta D'] = resultados_df['TOTAL VISA DEB'] + resultados_df['TOTAL MASTRO D']
    resultados_df['Tarjeta C'] = resultados_df['TOTAL TARJ. CRED']
    resultados_df['Total MP'] = resultados_df['TOTAL MERCADO']
    resultados_df['Total DNI'] = resultados_df['TOTAL DNI']
    resultados_df['% Tarjeta D'] = (resultados_df['Tarjeta D'] / resultados_df['TOTAL DIARIO'])*100
    resultados_df['% Tarjeta C'] = (resultados_df['Tarjeta C'] / resultados_df['TOTAL DIARIO'])*100
    resultados_df['% MP'] = (resultados_df['TOTAL MERCADO'] / resultados_df['TOTAL DIARIO'])*100
    resultados_df['% DNI'] = (resultados_df['TOTAL DNI'] / resultados_df['TOTAL DIARIO'])*100

    # Agregar la columna "Días" con un conteo simple
    resultados_df.insert(0, 'Días', range(1, len(resultados_df) + 1))
    resultados_df = resultados_df[encabezados_xls]

    # Calcular el conteo de días trabajados (último valor de la columna "Días")
    dias_trabajados = resultados_df['Días'].iloc[-1]

    # Calcular la suma de las columnas numéricas (excluyendo "Días")
    suma_columnas = resultados_df.select_dtypes(include=np.number).drop(columns=['Días']).sum()

    # Crear la última fila con los resultados
    ultima_fila = pd.Series({col: suma_columnas[col] for col in suma_columnas.index})
    ultima_fila.name = 'TOTALES'
    ultima_fila['Días'] = dias_trabajados

    # Agregar la última fila al DataFrame
    resultados_df = pd.concat([resultados_df, pd.DataFrame(ultima_fila).T])

    # Guardar el DataFrame en un archivo Excel
    resultados_df.to_excel(ruta_salida)

"""# Programa

### Forzar Reprocesamiento de un Mes Específico

Para que el sistema reprocese un archivo que ya está marcado como 'Processed', necesitamos cambiar manualmente su estado a 'Ready to Process' en el DataFrame `control_df`. Reemplaza `MES_A_REPROCESAR` con el número del mes que deseas reprocesar (por ejemplo, `1` para Enero, `11` para Noviembre).
"""

# Cambia este valor al número del mes que quieres reprocesar (ej. 1 para Enero, 11 para Noviembre)
MES_A_REPROCESAR = 1

# Asegurarse de que el control_df esté actualizado si no se ha ejecutado recientemente
# (Esta línea podría no ser necesaria si la celda principal ya se corrió justo antes)
control_df = load_or_create_control_sheet(os.path.join(RUTA_RAIZ, CARPETA_INFORMES, ANIOS[0]))

if not control_df[control_df['Mes'] == MES_A_REPROCESAR].empty:
    control_df.loc[control_df['Mes'] == MES_A_REPROCESAR, 'EstadoProcesamiento'] = STATUS_READY_TO_PROCESS
    control_df.loc[control_df['Mes'] == MES_A_REPROCESAR, 'FechaUltimoProcesamiento'] = pd.NaT # Reset timestamp
    print(f"El mes {MES_A_REPROCESAR} ha sido marcado como '{STATUS_READY_TO_PROCESS}'.")
    display(control_df[control_df['Mes'] == MES_A_REPROCESAR])

    # --- ADDED: Save the updated control_df to file ---
    ruta_informes_anio_actual = os.path.join(RUTA_RAIZ, CARPETA_INFORMES, ANIOS[0])
    control_sheet_path = os.path.join(ruta_informes_anio_actual, CONTROL_SHEET_FILENAME)
    try:
        control_df.to_excel(control_sheet_path, index=False)
        print(f"Hoja de control '{CONTROL_SHEET_FILENAME}' guardada con el estado actualizado para el mes {MES_A_REPROCESAR}.")
    except Exception as e:
        print(f"Error al guardar la hoja de control después de actualizar el mes {MES_A_REPROCESAR}: {e}")
    # --- END ADDED SECTION ---

else:
    print(f"Advertencia: El mes {MES_A_REPROCESAR} no se encontró en el control_df.")


print("\nAhora puedes volver a ejecutar la celda del programa principal para procesar este mes.")

"""```
,Días,B,N,D,,TOTAL DIARIO,Tarjeta D,Tarjeta C,Total MP,Total DNI,% Tarjeta D,% Tarjeta C,% MP,% DNI,GASTOS
```

```
B,N,D,,TOTAL DIARIO,Tarjeta D,GASTOS
```

## Main

### Auditoría de Extracción de Valores en una Hoja Específica

Esta celda cargará una hoja de ejemplo para inspeccionar el contenido de las columnas relevantes (P a S) y ver el resultado directo de la función `buscar_valores_adyacentes`.

**Hoja seleccionada para auditoría:**
- **Archivo:** `11-Noviembre-2025.xlsx`
- **Hoja:** `29-11`

Analizaremos la salida para entender por qué algunos valores podrían estar en `nan` o ser incorrectos.
"""

# Configuración para auditoría
import pandas as pd
import os

# Rutas (usando las definidas globalmente)
ruta_base_archivos = os.path.join(RUTA_RAIZ, CARPETA_PLANILLAS, '2025/')
nombre_archivo_auditar = '11-Noviembre-2025.xlsx'
nombre_hoja_auditar = '29-11'

ruta_archivo_completa = os.path.join(ruta_base_archivos, nombre_archivo_auditar)

print(f"\n--- AUDITORÍA DE HOJA: {nombre_hoja_auditar} en {nombre_archivo_auditar} ---")

try:
    # Leer la hoja específica, sin encabezados para una vista raw
    df_auditoria = pd.read_excel(ruta_archivo_completa, sheet_name=nombre_hoja_auditar, header=None)
    print("\n--- Datos RAW de la hoja de auditoría (Columnas P a S - Índices 15 a 18) ---")
    # Mostrar un rango de columnas alrededor de la columna P (índice 15)
    # Asegúrate de que el DataFrame tenga suficientes columnas
    if df_auditoria.shape[1] > 18:
        display(df_auditoria.iloc[:, 13:19]) # Mostrar de columna N a S (índices 13 a 18) para contexto
    else:
        display(df_auditoria.head())
        print("Advertencia: La hoja no tiene suficientes columnas para mostrar el rango P a S.")

    # Aplicar renombrado de valores específicos antes de la búsqueda
    df_renombrado_auditoria = renombrar_valores_df(df_auditoria, XLSX_CONFIG['renombres_especificos'])

    print("\n--- Resultado de buscar_valores_adyacentes con XLSX_CONFIG ---")
    # Ejecutar la función de búsqueda de valores adyacentes
    resultados_auditoria = buscar_valores_adyacentes(
        df_renombrado_auditoria,
        XLSX_CONFIG['encabezados_a_extraer'],
        XLSX_CONFIG['config_busqueda_valores'],
        search_column_index=XLSX_CONFIG['search_column_index']
    )
    display(resultados_auditoria)

except FileNotFoundError:
    print(f"ERROR: Archivo no encontrado: {ruta_archivo_completa}")
except Exception as e:
    print(f"ERROR inesperado durante la auditoría: {e}")

for anio in ANIOS:
    ruta_planillas_anio = os.path.join(RUTA_RAIZ, CARPETA_PLANILLAS, anio)
    ruta_informes_anio = os.path.join(RUTA_RAIZ, CARPETA_INFORMES, anio)

    logging.info(f"Procesando año: {anio.strip('/')}")
    logging.info(f"Directorio de planillas: {ruta_planillas_anio}")
    logging.info(f"Directorio de informes: {ruta_informes_anio}")

    if not os.path.isdir(ruta_planillas_anio):
        logging.warning(f"Directorio de planillas no encontrado: {ruta_planillas_anio}. Saltando año.")
        continue

    try:
        os.makedirs(ruta_informes_anio, exist_ok=True)
    except OSError as e:
        logging.error(f"No se pudo crear el directorio de informes '{ruta_informes_anio}': {e}. Saltando año.")
        continue

    control_df = load_or_create_control_sheet(ruta_informes_anio)

    logging.info(f"Estado inicial de control_df para {anio.strip('/')}:\n{control_df.to_string()}")

    control_df = update_control_sheet_with_files(control_df, ruta_planillas_anio)

    logging.info(f"Estado de control_df después de la actualización con archivos para {anio.strip('/')}:\n{control_df.to_string()}")

    files_to_process = control_df[
        control_df['EstadoProcesamiento'] == STATUS_READY_TO_PROCESS
    ]

    logging.info(f"Archivos listos para procesar para {anio.strip('/')}:\n{files_to_process.to_string()}")

    if files_to_process.empty:
        logging.info(f"No hay archivos '{STATUS_READY_TO_PROCESS}' para el año {anio.strip('/')}.")
    else:
        for index, row in files_to_process.iterrows():
            nombre_archivo_con_ext = row['NombreArchivo']
            mes_actual = row['Mes']

            ruta_archivo_completa = os.path.join(ruta_planillas_anio, nombre_archivo_con_ext)

            if os.path.isfile(ruta_archivo_completa):
                logging.info(f"Iniciando procesamiento del archivo: {nombre_archivo_con_ext} para el mes {mes_actual}")
                nombre_base, extension = os.path.splitext(nombre_archivo_con_ext)
                nombre_informe = f"informe de ventas {nombre_base}{extension}"
                ruta_salida_completa = os.path.join(ruta_informes_anio, nombre_informe)

                current_file_config = None
                if extension.lower() == '.ods':
                    current_file_config = ODS_CONFIG
                elif extension.lower() in ('.xlsx', '.xls'):
                    current_file_config = XLSX_CONFIG
                else:
                    logging.warning(f"Tipo de archivo desconocido para '{nombre_archivo_con_ext}'. Saltando este archivo.")
                    continue

                try:
                    procesar_archivo_excel(ruta_archivo_completa, ruta_salida_completa, current_file_config)

                    control_df.loc[control_df['Mes'] == mes_actual, 'EstadoProcesamiento'] = STATUS_PROCESSED
                    control_df.loc[control_df['Mes'] == mes_actual, 'FechaUltimoProcesamiento'] = datetime.datetime.now()
                    logging.info(f"Archivo '{nombre_archivo_con_ext}' procesado exitosamente y estado actualizado a '{STATUS_PROCESSED}'.")
                except Exception as e:
                    logging.error(f"Error al procesar el archivo '{nombre_archivo_con_ext}': {e}. El estado no se ha actualizado a procesado.")
            else:
                logging.warning(f"Archivo '{nombre_archivo_con_ext}' (para el mes {mes_actual}) no encontrado o no es un archivo válido en el directorio de planillas. No se procesará.")

    try:
        control_sheet_path = os.path.join(ruta_informes_anio, CONTROL_SHEET_FILENAME)
        control_df.to_excel(control_sheet_path, index=False)
        logging.info(f"Hoja de control '{CONTROL_SHEET_FILENAME}' guardada para el año {anio.strip('/')}.")
    except Exception as e:
        logging.error(f"Error al guardar la hoja de control para el año {anio.strip('/')}: {e}")

logging.info("Proceso de informes finalizado para todos los años configurados.")

import datetime
import logging
import pandas as pd
import numpy as np
import os
import sys # Import sys for explicit stdout handling
from typing import Dict, List, Tuple, Optional, Any

# --- Configuración Centralizada ---
RUTA_RAIZ = '/content/drive/MyDrive/Proveedores en automatico/Contaduria y Control/Informes Ferreteria/'
CARPETA_PLANILLAS = 'Planillas diarias/'
CARPETA_INFORMES = 'Informes Finales/'
ANIOS = ['2025/',]

TEXTO_GASTOS_ORIGINAL = 'GASTOS'
TEXTO_GASTOS_MODIFICADO = 'TABLA GASTOS'

COMMON_RENAMES = {
    'total dni': 'TOTAL DNI',
    'TOTAL DURACRIL': 'TOTAL DNI',
}

COLUMNAS_INFORME_FINAL = [
    'Días', 'B', 'N', 'D', '', 'TOTAL DIARIO', 'Tarjeta D', 'Tarjeta C',
    'Total MP', 'Total DNI', '% Tarjeta D', '% Tarjeta C', '% MP', '% DNI',
    TEXTO_GASTOS_ORIGINAL
]

ODS_CONFIG = {
    'renombres_especificos': {
        **COMMON_RENAMES,
        'TOTAL TARJ. CREDITO': 'TOTAL TARJ. CRED',
        'TOTAL MASTRO DEBITO': 'TOTAL MASTRO D'
    },
    'encabezados_a_extraer': [
        'Z', 'N', 'DIFERENCIA', 'VENTA FINAL', 'TOTAL TARJ. CRED',
        'TOTAL VISA DEB', 'TOTAL MASTRO D', 'TOTAL MERCADO', 'TOTAL DNI',
        TEXTO_GASTOS_ORIGINAL
    ],
    'config_busqueda_valores': {
        'grupos': [
            {
                'nombres': ['TOTAL TARJ. CRED', 'TOTAL MERCADO', 'TOTAL DNI'],
                'offset': 2,
                'nan_a_cero': True
            },
        ],
        'default': {
            'offset': 1,
            'nan_a_cero': False
        }
    },
    'venta_final_key': 'VENTA FINAL',
    'tarjeta_d_key1': 'TOTAL VISA DEB',
    'tarjeta_d_key2': 'TOTAL MASTRO D',
    'tarjeta_c_key': 'TOTAL TARJ. CRED',
    'mp_key': 'TOTAL MERCADO', # NEW
    'dni_key': 'TOTAL DNI',     # NEW
    'search_column_index': None,
    'columnas_informe_final': COLUMNAS_INFORME_FINAL
}

XLSX_CONFIG = {
    'renombres_especificos': {
        **COMMON_RENAMES,
    },
    'encabezados_a_extraer': [
        'Z', 'N', 'DIFERENCIA', 'VENTA BRUTA', 'CREDITO', 'DEBITO', 'MAESTRO',
        'MP', 'DNI', # Changed from 'TOTAL MERCADO', 'TOTAL DNI'
        TEXTO_GASTOS_ORIGINAL
    ],
    'config_busqueda_valores': {
        'grupos': [
            {
                'nombres': [
                    'Z', 'N', 'DIFERENCIA', 'VENTA BRUTA', 'CREDITO', 'DEBITO', 'MAESTRO',
                    'MP', 'DNI', # Changed from 'TOTAL MERCADO', 'TOTAL DNI'
                    TEXTO_GASTOS_ORIGINAL
                ],
                'offset': 2,
                'nan_a_cero': True,
                'search_column_index': 15 # Column 'P' (0-indexed)
            }
        ],
        'default': {
            'offset': 2,
            'nan_a_cero': True
        }
    },
    'venta_final_key': 'VENTA BRUTA',
    'tarjeta_d_key1': 'DEBITO',
    'tarjeta_d_key2': 'MAESTRO',
    'tarjeta_c_key': 'CREDITO',
    'mp_key': 'MP', # NEW
    'dni_key': 'DNI', # NEW
    'search_column_index': None,
    'columnas_informe_final': COLUMNAS_INFORME_FINAL
}

CONTROL_SHEET_FILENAME = '_control.xlsx'
CONTROL_COLUMNS = ['Mes', 'NombreArchivo', 'EstadoProcesamiento', 'FechaUltimoProcesamiento']
STATUS_UNPROCESSED = 'Unprocessed'
STATUS_READY_TO_PROCESS = 'Ready to Process'
STATUS_PROCESSED = 'Processed'

# --- Configuración de Logging explícita para Colab ---
# Eliminar cualquier handler existente para evitar duplicados si la celda se ejecuta múltiples veces
for handler in logging.root.handlers[:]:
    logging.root.removeHandler(handler)

# Configurar el logger raíz
logging.root.setLevel(logging.DEBUG) # Nivel de logging a DEBUG para máxima verbosidad
formatter = logging.Formatter('%(asctime)s - %(levelname)s - %(message)s')

# Crear un StreamHandler que escribe a sys.stdout
console_handler = logging.StreamHandler(sys.stdout)
console_handler.setLevel(logging.DEBUG)
console_handler.setFormatter(formatter)

# Añadir el handler al logger raíz
logging.root.addHandler(console_handler)

logging.debug("Configuración de logging establecida en DEBUG y dirigida a sys.stdout.") # Test message

# --- Functions Refactorizadas ---

def leer_todas_las_hojas(filename: str) -> Optional[Tuple[Dict[str, pd.DataFrame], List[str]]]:
    if not os.path.isfile(filename):
        logging.error(f"Archivo no encontrado: {filename}")
        return None
    try:
        if filename.lower().endswith(('.ods')):
            with pd.ExcelFile(filename, engine='odf') as xls:
                sheets = xls.sheet_names
                all_data = pd.read_excel(xls, sheet_name=None, header=None, engine='odf')
        else:
            with pd.ExcelFile(filename) as xls:
                sheets = xls.sheet_names
                all_data = pd.read_excel(xls, sheet_name=None, header=None)

        logging.info(f"Leídas {len(sheets)} hojas del archivo: {filename}")
        return all_data, sheets
    except Exception as e:
        logging.error(f"Error al leer el archivo Excel '{filename}': {e}")
        return None

def modificar_primer_gasto(df: pd.DataFrame, texto_buscar: str, texto_reemplazar: str, max_filas_buscar: int = 40) -> pd.DataFrame:
    df_copy = df.copy()
    try:
        df_subset = df_copy.iloc[:max_filas_buscar]
        coords = np.argwhere(df_subset.values == texto_buscar)
        if coords.size > 0:
            fila, columna = coords[0]
            df_copy.iloc[fila, columna] = texto_reemplazar
    except Exception as e:
        logging.warning(f"Error durante la modificación de '{texto_buscar}': {e}")
    return df_copy

def renombrar_valores_df(df: pd.DataFrame, reemplazos: Dict[str, str]) -> pd.DataFrame:
    df_copy = df.copy()
    try:
        df_copy = df_copy.replace(reemplazos)
    except Exception as e:
        logging.warning(f"Ocurrió un error durante el renombrado de valores: {e}")
    return df_copy

def buscar_valores_adyacentes(df: pd.DataFrame, encabezados: List[str], config: Dict, search_column_index: Optional[int] = None) -> Dict[str, Any]:
    resultados = {enc: None for enc in encabezados}
    logging.debug(f"Iniciando búsqueda adyacente para: {encabezados}")
    logging.debug(f"Buscando en columna específica (si está definida): {search_column_index}")

    config_map = {}
    default_cfg = config.get('default', {'offset': 1, 'nan_a_cero': False})
    logging.debug(f"DEBUG: default_cfg determined as: {default_cfg}")
    for grupo in config.get('grupos', []):
        cfg = default_cfg.copy()
        cfg.update(grupo)
        for nombre in grupo.get('nombres', []):
            config_map[nombre] = cfg

    df_values = df.values

    for encabezado in encabezados:
        try:
            fila = -1
            columna_base = -1

            # Determine search column for current header, prioritize group-specific over global
            current_search_col_idx = config_map.get(encabezado, {}).get('search_column_index', search_column_index)
            logging.debug(f"  Buscando encabezado '{encabezado}'. Columna de búsqueda efectiva: {current_search_col_idx}")

            if current_search_col_idx is not None and 0 <= current_search_col_idx < df_values.shape[1]:
                # Search only in the specified column
                column_slice = df_values[:, current_search_col_idx]
                relative_coords = np.argwhere(column_slice == encabezado)
                if relative_coords.size > 0:
                    fila = relative_coords[0][0]
                    columna_base = current_search_col_idx # The fixed column for search
                    logging.debug(f"Encabezado '{encabezado}' encontrado en ({fila}, {columna_base}) (columna restringida {current_search_col_idx}).")
                else:
                    logging.debug(f"Encabezado '{encabezado}' no encontrado en la columna {current_search_col_idx}.")
                    continue # Move to next header if not found in restricted column
            else:
                # Search entire DataFrame (if no specific column is set or it's out of bounds)
                coords = np.argwhere(df_values == encabezado)
                if coords.size > 0:
                    fila, columna_base = coords[0]
                    logging.debug(f"Encabezado '{encabezado}' encontrado en ({fila}, {columna_base}) (búsqueda completa).")
                else:
                    logging.debug(f"Encabezado '{encabezado}' no encontrado en la hoja.")
                    continue # Move to next header if not found

            # If we reached here, an encabezado was found
            cfg_actual = config_map.get(encabezado, default_cfg)
            logging.debug(f"  DEBUG: cfg_actual for '{encabezado}': {cfg_actual}") # Detailed debug
            offset = cfg_actual.get('offset', 1)
            convertir_nan = cfg_actual.get('nan_a_cero', False)
            logging.debug(f"  Config para '{encabezado}': offset={offset}, nan_a_cero={convertir_nan}")

            columna_valor = columna_base + offset

            if 0 <= columna_valor < df_values.shape[1]:
                valor_celda = df_values[fila, columna_valor]
                logging.debug(f"  Valor crudo en ({fila}, {columna_valor}): {valor_celda}")
                if convertir_nan and pd.isna(valor_celda):
                    resultados[encabezado] = 0
                    logging.debug(f"  Valor es NaN/NaT, convirtiendo a 0.")
                else:
                    resultados[encabezado] = valor_celda
            else:
                logging.warning(f"Columna calculada {columna_valor} (offset {offset}) fuera de límites para '{encabezado}'.")

        except Exception as e:
            logging.error(f"Error procesando el encabezado '{encabezado}': {e}")

        logging.debug(f"  -> Resultado final para '{encabezado}': {resultados[encabezado]}")

    logging.debug("Fin búsqueda adyacente.")
    return resultados

def procesar_hoja(df_original: pd.DataFrame, config: Dict) -> Optional[Dict[str, Any]]:
    """
    Aplica las transformaciones (modificar gasto, renombrar, buscar valores) a un DataFrame de una hoja.
    La 'config' aquí es ODS_CONFIG o XLSX_CONFIG completa.
    """
    try:
        # 1. Modificar 'GASTOS' (si aún es necesario)
        # df_mod = modificar_primer_gasto(df_original, TEXTO_GASTOS_ORIGINAL, TEXTO_GASTOS_MODIFICADO)
        df_mod = df_original # O la copia si es necesario df_original.copy()

        # 2. Renombrar valores específicos
        df_renombrado = renombrar_valores_df(df_mod, config['renombres_especificos'])

        # 3. Buscar valores finales, pasando el search_column_index si existe
        search_col_idx = config.get('search_column_index', None)
        valores_extraidos = buscar_valores_adyacentes(
            df_renombrado,
            config['encabezados_a_extraer'],
            config['config_busqueda_valores'],
            search_column_index=search_col_idx # Pass the new parameter
        )
        return valores_extraidos
    except Exception as e:
        logging.error(f"Error procesando una hoja: {e}")
        return None


def calcular_columnas_informe(
    df_extraido: pd.DataFrame,
    col_gastos: str,
    venta_final_key: str,
    tarjeta_d_key1: str,
    tarjeta_d_key2: str,
    tarjeta_c_key: str,
    mp_key: str, # NEW PARAMETER
    dni_key: str # NEW PARAMETER
) -> pd.DataFrame:
    df = df_extraido.copy()
    logging.debug(f"DataFrame before numeric conversion in calcular_columnas_informe:\n{df.head()}") # Debug print

    cols_numericas = [
        'Z', 'N', 'DIFERENCIA', venta_final_key, tarjeta_c_key,
        tarjeta_d_key1, tarjeta_d_key2, mp_key, dni_key, # Changed: use mp_key and dni_key
        col_gastos
    ]
    for col in cols_numericas:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors='coerce')

    logging.debug(f"DataFrame after numeric conversion and before fillna(0) for {col_gastos}:\n{df.head()}") # Debug print
    df[col_gastos] = df[col_gastos].fillna(0)
    numeric_cols_to_fill = [
        'Z', 'N', 'DIFERENCIA', venta_final_key, tarjeta_c_key,
        tarjeta_d_key1, tarjeta_d_key2, mp_key, dni_key # Changed: use mp_key and dni_key
    ]
    for col in numeric_cols_to_fill:
         if col in df.columns:
             df[col] = df[col].fillna(0)

    logging.debug(f"DataFrame after all fillna(0):\n{df.head()}") # Debug print

    df['B'] = df.get('Z', 0) # Usar .get con default por si falta la columna
    df['D'] = df.get('DIFERENCIA', 0)
    df['TOTAL DIARIO'] = df.get(venta_final_key, 0)
    df[''] = '' # Columna vacía
    df['Tarjeta D'] = df.get(tarjeta_d_key1, 0) + df.get(tarjeta_d_key2, 0)
    df['Tarjeta C'] = df.get(tarjeta_c_key, 0)
    df['Total MP'] = df.get(mp_key, 0) # Changed: use mp_key
    df['Total DNI'] = df.get(dni_key, 0) # Changed: use dni_key

    logging.debug(f"DataFrame before percentage calculations:\n{df.head()}") # Debug print

    total_diario = df['TOTAL DIARIO']
    divisor_seguro = np.where(total_diario == 0, 1, total_diario) # Evita dividir por 0, resultado será x/1

    df['% Tarjeta D'] = np.divide(df['Tarjeta D'], divisor_seguro, out=np.zeros_like(df['Tarjeta D'], dtype=float), where=divisor_seguro!=0) * 100
    df['% Tarjeta C'] = np.divide(df['Tarjeta C'], divisor_seguro, out=np.zeros_like(df['Tarjeta C'], dtype=float), where=divisor_seguro!=0) * 100
    df['% MP'] = np.divide(df['Total MP'], divisor_seguro, out=np.zeros_like(df['Total MP'], dtype=float), where=divisor_seguro!=0) * 100
    df['% DNI'] = np.divide(df['Total DNI'], divisor_seguro, out=np.zeros_like(df['Total DNI'], dtype=float), where=divisor_seguro!=0) * 100

    return df

def agregar_fila_totales(df: pd.DataFrame, col_dias: str = 'Días') -> pd.DataFrame:
    """Calcula y agrega una fila de totales al DataFrame."""
    logging.info("Agregando fila de totales...")
    if df.empty:
        logging.warning("DataFrame vacío, no se puede agregar fila de totales.")
        return df

    # Seleccionar solo columnas numéricas para sumar, excluyendo la de días si existe
    numeric_cols = df.select_dtypes(include=np.number).columns
    if col_dias in numeric_cols:
        numeric_cols = numeric_cols.drop(col_dias)

    # Calcular suma solo si hay columnas numéricas
    if not numeric_cols.empty:
        suma_columnas = df[numeric_cols].sum()
        # Crear la fila de totales como un DataFrame para concatenar fácilmente
        ultima_fila = pd.DataFrame(suma_columnas).T
        ultima_fila.index = ['TOTALES'] # Nombrar el índice de la fila
    else:
        # Crear una fila vacía con el índice 'TOTALES' si no hay nada que sumar
         ultima_fila = pd.DataFrame(index=['TOTALES'], columns=df.columns)


    # Añadir el conteo de días trabajados
    if col_dias in df.columns and not df.empty:
       # Asegurarse de que la columna 'Días' exista y no esté vacía
       # Tomar el último valor numérico de la columna 'Días'
       dias_validos = pd.to_numeric(df[col_dias], errors='coerce').dropna()
       if not dias_validos.empty:
           ultima_fila[col_dias] = dias_validos.iloc[-1]
       else:
           ultima_fila[col_dias] = 0 # O manejar como prefieras si no hay días válidos
    elif col_dias not in df.columns:
         ultima_fila[col_dias] = len(df) # Alternativa si no hay col Días: contar filas


    # Concatenar la fila de totales
    df_con_totales = pd.concat([df, ultima_fila], ignore_index=False) # Mantener índice original + 'TOTALES'
    logging.info("Fila de totales agregada.")
    return df_con_totales

def procesar_archivo_excel(ruta_archivo: str, ruta_salida: str, config: Dict):
    """
    Orquesta el procesamiento completo de un único archivo Excel.
    """
    logging.info(f"--- Iniciando procesamiento para: {ruta_archivo} ---")

    lectura_result = leer_todas_las_hojas(ruta_archivo)
    if lectura_result is None:
        return # Error ya loggeado en la función de lectura

    datos_por_hoja, hojas_leidas = lectura_result
    resultados_hojas = {}

    for nombre_hoja, df_hoja in datos_por_hoja.items():
        logging.info(f"--- Procesando Hoja: {nombre_hoja} ---")
        # Pass the 'current_file_config' (which is 'config' in this function) directly to procesar_hoja
        resultado_hoja = procesar_hoja(df_hoja, config)
        if resultado_hoja:
            resultados_hojas[nombre_hoja] = resultado_hoja
        else:
            logging.warning(f"No se pudo procesar la hoja: {nombre_hoja}")

    if not resultados_hojas:
        logging.warning(f"No se obtuvieron resultados de ninguna hoja en {ruta_archivo}. No se generará informe.")
        return

    # Convertir resultados a DataFrame
    resultados_df = pd.DataFrame.from_dict(resultados_hojas, orient='index')

    # Filtrar filas cuyo índice (nombre de hoja) contenga '-'
    # Asegurarse de que el índice sea string para la operación .str
    resultados_df.index = resultados_df.index.astype(str)
    resultados_df = resultados_df[resultados_df.index.str.contains('-')]

    if resultados_df.empty:
        logging.warning(f"No quedaron hojas válidas (con '-') tras el filtrado en {ruta_archivo}. No se generará informe.")
        return

    # Calcular columnas derivadas
    df_calculado = calcular_columnas_informe(resultados_df,
                                              col_gastos=TEXTO_GASTOS_ORIGINAL, # Usar constante
                                              venta_final_key=config['venta_final_key'], # Acceder directamente de la config
                                              tarjeta_d_key1=config['tarjeta_d_key1'],
                                              tarjeta_d_key2=config['tarjeta_d_key2'],
                                              tarjeta_c_key=config['tarjeta_c_key'],
                                              mp_key=config['mp_key'], # NEW
                                              dni_key=config['dni_key']) # NEW

    # Agregar columna "Días"
    df_calculado.insert(0, 'Días', range(1, len(df_calculado) + 1))

    # Reordenar y seleccionar columnas finales
    columnas_finales = config.get('columnas_informe_final', df_calculado.columns.tolist())
    # Asegurarse de que solo se incluyan columnas que existen en el df
    columnas_existentes = [col for col in columnas_finales if col in df_calculado.columns]
    df_final = df_calculado[columnas_existentes]


    # Agregar fila de totales
    df_con_totales = agregar_fila_totales(df_final, col_dias='Días')

    # Guardar el informe
    try:
        logging.info(f"Guardando informe final en: {ruta_salida}")
        # Crear directorio si no existe
        os.makedirs(os.path.dirname(ruta_salida), exist_ok=True)
        # Guardar sin el índice del DataFrame en el Excel
        df_con_totales.to_excel(ruta_salida, index=True) # index=True para mantener 'TOTALES' como índice
        logging.info(f"Informe guardado exitosamente.")
    except Exception as e:
        logging.error(f"Error al guardar el archivo Excel '{ruta_salida}': {e}")

    logging.info(f"--- Fin del procesamiento para: {ruta_archivo} ---")

def extract_month_from_filename(filename: str) -> int | None:
    if not isinstance(filename, str) or len(filename) < 2:
        return None
    try:
        month_str = filename[:2]
        month = int(month_str)
        if 1 <= month <= 12:
            return month
        else:
            return None
    except ValueError:
        return None
    except Exception as e:
        return None

def load_or_create_control_sheet(year_reports_path: str) -> pd.DataFrame:
    control_sheet_path = os.path.join(year_reports_path, CONTROL_SHEET_FILENAME)

    if os.path.exists(control_sheet_path):
        try:
            control_df = pd.read_excel(control_sheet_path)
            control_df['FechaUltimoProcesamiento'] = pd.to_datetime(control_df['FechaUltimoProcesamiento'], errors='coerce')
            control_df['NombreArchivo'] = control_df['NombreArchivo'].astype(str).replace('nan', None)
            return control_df
        except Exception as e:
            logging.error(f"Error al cargar la hoja de control existente '{control_sheet_path}': {e}")
            pass

    data = {
        'Mes': list(range(1, 13)),
        'NombreArchivo': [None] * 12,
        'EstadoProcesamiento': [STATUS_UNPROCESSED] * 12,
        'FechaUltimoProcesamiento': [pd.NaT] * 12
    }
    control_df = pd.DataFrame(data, columns=CONTROL_COLUMNS)
    control_df['FechaUltimoProcesamiento'] = pd.to_datetime(control_df['FechaUltimoProcesamiento'])

    try:
        os.makedirs(year_reports_path, exist_ok=True)
        control_df.to_excel(control_sheet_path, index=False)
    except Exception as e:
        logging.error(f"Error al guardar la nueva hoja de control '{control_sheet_path}': {e}")
        pass

    return control_df

def update_control_sheet_with_files(control_df: pd.DataFrame, current_year_planillas_path: str) -> pd.DataFrame:
    updated_control_df = control_df.copy()

    if not os.path.exists(current_year_planillas_path):
        logging.warning(f"Ruta de planillas no encontrada: {current_year_planillas_path}")
        return updated_control_df

    try:
        files_in_folder = os.listdir(current_year_planillas_path)
    except Exception as e:
        logging.error(f"Error al listar archivos en '{current_year_planillas_path}': {e}")
        return updated_control_df

    processed_months_from_folder = set()  # To track months for which a valid file was found in the actual folder

    for filename_with_ext in files_in_folder:
        full_path = os.path.join(current_year_planillas_path, filename_with_ext)
        if os.path.isfile(full_path) and \
           filename_with_ext.lower().endswith(('.xlsx', '.xls', '.ods')):

            month = extract_month_from_filename(filename_with_ext)

            if month is not None:
                row_index = updated_control_df[updated_control_df['Mes'] == month].index

                if not row_index.empty:
                    idx = row_index[0]
                    current_status = updated_control_df.loc[idx, 'EstadoProcesamiento']
                    recorded_filename = updated_control_df.loc[idx, 'NombreArchivo']

                    # Use pd.isna for robustness against NaN in recorded_filename
                    if pd.isna(recorded_filename) or str(recorded_filename).lower() == 'none':
                        # Case 1: New file for this month slot
                        logging.info(f"Mes {month}: Nuevo archivo detectado '{filename_with_ext}'. Estado actualizado a '{STATUS_READY_TO_PROCESS}'.")
                        updated_control_df.at[idx, 'NombreArchivo'] = filename_with_ext
                        updated_control_df.at[idx, 'EstadoProcesamiento'] = STATUS_READY_TO_PROCESS
                    elif recorded_filename != filename_with_ext:
                        # Case 2: Filename changed for this month slot
                        logging.info(f"Mes {month}: Archivo ha cambiado de '{recorded_filename}' a '{filename_with_ext}'. Estado actualizado a '{STATUS_READY_TO_PROCESS}'.")
                        updated_control_df.at[idx, 'NombreArchivo'] = filename_with_ext
                        updated_control_df.at[idx, 'EstadoProcesamiento'] = STATUS_READY_TO_PROCESS
                    elif current_status != STATUS_PROCESSED:
                        # Case 3: File found, filename unchanged, but status is not 'Processed'
                        logging.info(f"Mes {month}: Archivo '{filename_with_ext}' encontrado y no procesado ('{current_status}'). Estado actualizado a '{STATUS_READY_TO_PROCESS}'.")
                        updated_control_df.at[idx, 'EstadoProcesamiento'] = STATUS_READY_TO_PROCESS
                    else:
                        # Case 4: File found, filename unchanged, and status is 'Processed'
                        logging.info(f"Mes {month}: Archivo '{filename_with_ext}' ya procesado y sin cambios. Estado '{STATUS_PROCESSED}'.")
                    processed_months_from_folder.add(month)
                else:
                    logging.warning(f"Mes {month} (de archivo '{filename_with_ext}') no encontrado en la hoja de control. Este archivo será ignorado.")
            else:
                logging.warning(f"No se pudo extraer el mes del nombre de archivo '{filename_with_ext}'. Este archivo será ignorado.")
        else:
            logging.debug(f"Omitiendo '{filename_with_ext}': no es un archivo o no es un tipo de Excel/ODS reconocido.")

    # After iterating through all files in the folder, check for months in control_df that didn't have a matching file
    for index, row in updated_control_df.iterrows():
        month_in_control = row['Mes']
        recorded_filename_in_control = row['NombreArchivo']
        status_in_control = row['EstadoProcesamiento']

        if month_in_control not in processed_months_from_folder:
            if pd.isna(recorded_filename_in_control) or str(recorded_filename_in_control).lower() == 'none':
                logging.debug(f"Mes {month_in_control}: No se encontró un archivo en la carpeta para este mes, y no hay un nombre de archivo registrado. Manteniendo estado '{STATUS_UNPROCESSED}'.")
            else:
                # This means a file was previously recorded for this month, but it's no longer in the folder.
                logging.warning(f"Mes {month_in_control}: El archivo registrado '{recorded_filename_in_control}' no se encontró en la carpeta actual. Estableciendo estado a '{STATUS_READY_TO_PROCESS}' para revisión, y borrando el nombre de archivo registrado.")
                updated_control_df.at[index, 'EstadoProcesamiento'] = STATUS_READY_TO_PROCESS  # Mark for attention
                updated_control_df.at[index, 'NombreArchivo'] = None  # Clear the filename as it's missing

    logging.info("Actualización de hoja de control completada.")
    return updated_control_df

# --- Bucle Principal Modificado ---

for anio in ANIOS:
    ruta_planillas_anio = os.path.join(RUTA_RAIZ, CARPETA_PLANILLAS, anio)
    ruta_informes_anio = os.path.join(RUTA_RAIZ, CARPETA_INFORMES, anio)

    logging.info(f"Procesando año: {anio.strip('/')}")
    logging.info(f"Directorio de planillas: {ruta_planillas_anio}")
    logging.info(f"Directorio de informes: {ruta_informes_anio}")

    if not os.path.isdir(ruta_planillas_anio):
        logging.warning(f"Directorio de planillas no encontrado: {ruta_planillas_anio}. Saltando año.")
        continue

    try:
        os.makedirs(ruta_informes_anio, exist_ok=True)
    except OSError as e:
        logging.error(f"No se pudo crear el directorio de informes '{ruta_informes_anio}': {e}. Saltando año.")
        continue

    control_df = load_or_create_control_sheet(ruta_informes_anio)

    logging.info(f"Estado inicial de control_df para {anio.strip('/')}:\n{control_df.to_string()}")

    control_df = update_control_sheet_with_files(control_df, ruta_planillas_anio)

    logging.info(f"Estado de control_df después de la actualización con archivos para {anio.strip('/')}:\n{control_df.to_string()}")

    files_to_process = control_df[
        control_df['EstadoProcesamiento'] == STATUS_READY_TO_PROCESS
    ]

    logging.info(f"Archivos listos para procesar para {anio.strip('/')}:\n{files_to_process.to_string()}")

    if files_to_process.empty:
        logging.info(f"No hay archivos '{STATUS_READY_TO_PROCESS}' para el año {anio.strip('/')}.")
    else:
        for index, row in files_to_process.iterrows():
            nombre_archivo_con_ext = row['NombreArchivo']
            mes_actual = row['Mes']

            ruta_archivo_completa = os.path.join(ruta_planillas_anio, nombre_archivo_con_ext)

            if os.path.isfile(ruta_archivo_completa):
                logging.info(f"Iniciando procesamiento del archivo: {nombre_archivo_con_ext} para el mes {mes_actual}")
                nombre_base, extension = os.path.splitext(nombre_archivo_con_ext)
                nombre_informe = f"informe de ventas {nombre_base}{extension}"
                ruta_salida_completa = os.path.join(ruta_informes_anio, nombre_informe)

                current_file_config = None
                if extension.lower() == '.ods':
                    current_file_config = ODS_CONFIG
                elif extension.lower() in ('.xlsx', '.xls'):
                    current_file_config = XLSX_CONFIG
                else:
                    logging.warning(f"Tipo de archivo desconocido para '{nombre_archivo_con_ext}'. Saltando este archivo.")
                    continue

                try:
                    procesar_archivo_excel(ruta_archivo_completa, ruta_salida_completa, current_file_config)

                    control_df.loc[control_df['Mes'] == mes_actual, 'EstadoProcesamiento'] = STATUS_PROCESSED
                    control_df.loc[control_df['Mes'] == mes_actual, 'FechaUltimoProcesamiento'] = datetime.datetime.now()
                    logging.info(f"Archivo '{nombre_archivo_con_ext}' procesado exitosamente y estado actualizado a '{STATUS_PROCESSED}'.")
                except Exception as e:
                    logging.error(f"Error al procesar el archivo '{nombre_archivo_con_ext}': {e}. El estado no se ha actualizado a procesado.")
            else:
                logging.warning(f"Archivo '{nombre_archivo_con_ext}' (para el mes {mes_actual}) no encontrado o no es un archivo válido en el directorio de planillas. No se procesará.")

    try:
        control_sheet_path = os.path.join(ruta_informes_anio, CONTROL_SHEET_FILENAME)
        control_df.to_excel(control_sheet_path, index=False)
        logging.info(f"Hoja de control '{CONTROL_SHEET_FILENAME}' guardada para el año {anio.strip('/')}.")
    except Exception as e:
        logging.error(f"Error al guardar la hoja de control para el año {anio.strip('/')}: {e}")

logging.info("Proceso de informes finalizado para todos los años configurados.")

"""# Task
Process sales spreadsheets for all years defined in the `ANIOS` variable. This involves dynamically generating paths for planilla and final report folders, creating report folders as needed, managing and updating a separate control sheet (`_control.xlsx`) for each year, and processing each monthly file according to its specific type (ODS or XLSX) and configuration, ensuring all processing states are recorded.

## Configuración de Años Dinámica

### Subtask:
Verificar y asegurar que la variable `ANIOS` en la celda `P4V0TAMtp7rd` contenga una lista de todos los años que se desean procesar. Esto es fundamental porque el bucle principal iterará sobre esta lista para cada año.

### Subtask:
Verificar y asegurar que la variable `ANIOS` en la celda `P4V0TAMtp7rd` contenga una lista de todos los años que se desean procesar. Esto es fundamental porque el bucle principal iterará sobre esta lista para cada año.

#### Instructions
1. Localiza la celda `P4V0TAMtp7rd` en tu cuaderno. El contenido actual es:

```python
RUTA_RAIZ = '/content/drive/MyDrive/Proveedores en automatico/Contaduria y Control/Informes Ferreteria/'
CARPETA_PLANILLAS = 'Planillas diarias/'
CARPETA_INFORMES = 'Informes Finales/'

ANIOS = [
    #'2024/',
    #'2025/',
    '2026/',
]
```

2. Edita la lista asignada a la variable `ANIOS` para incluir todos los años (como strings, seguidos de un '/') para los que deseas procesar los informes. Por ejemplo, si deseas procesar los años 2024 y 2025, la variable debería verse como `ANIOS = ['2024/', '2025/']`.

Después de editar la celda, asegúrate de ejecutarla para aplicar los cambios.

## Generación de Rutas Específicas por Año

### Subtask:
Asegurarse de que las rutas a las carpetas de planillas (`ruta_planillas_anio`) y a las carpetas de informes finales (`ruta_informes_anio`) se construyan dinámicamente dentro del bucle principal, utilizando el año actual de la iteración. Esto garantiza que el sistema busque archivos y guarde informes en el directorio correcto para cada año.

## Creación Dinámica de Carpetas de Informes

### Subtask:
Confirmar que el código dentro del bucle principal verifica si la carpeta de destino para los informes de un año específico (`ruta_informes_anio`) existe, y la crea automáticamente si no es así. Esto evita errores `FileNotFoundError` y asegura una estructura de carpetas limpia y organizada para cada año.

## Manejo de Hoja de Control por Año

### Subtask:
Asegurar que la hoja de control (`_control.xlsx`) sea cargada o creada de forma independiente para cada año dentro del bucle principal. Cada año debe tener su propia hoja de control que registre el estado de procesamiento de sus archivos mensuales, lo que permite un seguimiento y reprocesamiento granular.

### Verificación de Manejo de Hoja de Control por Año

Se ha confirmado que la implementación actual en la celda `jWoNP2JxRlxf` ya cumple con los requisitos de la subtarea:

1.  **Localización del Bucle Principal:** El bucle `for anio in ANIOS:` es el bucle principal que itera sobre los años configurados.
2.  **Llamada a `load_or_create_control_sheet`:** La función `control_df = load_or_create_control_sheet(ruta_informes_anio)` se llama dentro de este bucle.
3.  **Variable `ruta_informes_anio`:** Esta variable se construye como `os.path.join(RUTA_RAIZ, CARPETA_INFORMES, anio)`, lo que asegura que `ruta_informes_anio` es única para cada año y cambia en cada iteración del bucle.
4.  **Funcionalidad de `load_or_create_control_sheet`:** La función está diseñada para:
    *   Intentar cargar un archivo `_control.xlsx` de la `ruta_informes_anio` específica del año.
    *   Si el archivo no existe o hay un error al cargarlo, crea un nuevo DataFrame de control y lo guarda en esa misma ruta específica del año.

Por lo tanto, cada año gestiona su propia hoja de control de forma independiente, permitiendo un seguimiento y reprocesamiento granular como se solicitó.

## Actualización y Guardado Anual de Hoja de Control

### Subtask:
Verificar que la hoja de control (`_control.xlsx`) se actualice y guarde de forma independiente para cada año dentro del bucle principal.

El código en la celda `jWoNP2JxRlxf` ya cumple con los requisitos:

1.  **Actualización del `control_df`**: Dentro del bucle `for anio in ANIOS:`, la línea `control_df = update_control_sheet_with_files(control_df, ruta_planillas_anio)` asegura que la hoja de control se actualiza para el año específico (`ruta_planillas_anio`) de la iteración actual. Los mensajes de log (`logging.info`) antes y después de esta llamada lo demuestran.

2.  **Guardado independiente**: Al final de cada iteración del bucle anual, hay un bloque `try-except` que realiza el guardado:
    ```python
    try:
        control_sheet_path = os.path.join(ruta_informes_anio, CONTROL_SHEET_FILENAME)
        control_df.to_excel(control_sheet_path, index=False)
        logging.info(f"Hoja de control '{CONTROL_SHEET_FILENAME}' guardada para el año {anio.strip('/')}.")
    except Exception as e:
        logging.error(f"Error al guardar la hoja de control para el año {anio.strip('/')}: {e}")
    ```
    Aquí, `control_sheet_path` se construye utilizando `ruta_informes_anio`, lo que garantiza que la hoja de control se guarde en la carpeta de informes específica para cada año, y los `logging.info` confirman la acción de guardado anual.

El código en la celda `jWoNP2JxRlxf` ya cumple con los requisitos:

1.  **Actualización del `control_df`**: Dentro del bucle `for anio in ANIOS:`, la línea `control_df = update_control_sheet_with_files(control_df, ruta_planillas_anio)` asegura que la hoja de control se actualiza para el año específico (`ruta_planillas_anio`) de la iteración actual. Los mensajes de log (`logging.info`) antes y después de esta llamada lo demuestran.

2.  **Guardado independiente**: Al final de cada iteración del bucle anual, hay un bloque `try-except` que realiza el guardado:
    ```python
    try:
        control_sheet_path = os.path.join(ruta_informes_anio, CONTROL_SHEET_FILENAME)
        control_df.to_excel(control_sheet_path, index=False)
        logging.info(f"Hoja de control '{CONTROL_SHEET_FILENAME}' guardada para el año {anio.strip('/')}.")
    except Exception as e:
        logging.error(f"Error al guardar la hoja de control para el año {anio.strip('/')}: {e}")
    ```
    Aquí, `control_sheet_path` se construye utilizando `ruta_informes_anio`, lo que garantiza que la hoja de control se guarde en la carpeta de informes específica para cada año, y los `logging.info` confirman la acción de guardado anual.

El código en la celda `jWoNP2JxRlxf` ya cumple con los requisitos:

1.  **Actualización del `control_df`**: Dentro del bucle `for anio in ANIOS:`, la línea `control_df = update_control_sheet_with_files(control_df, ruta_planillas_anio)` asegura que la hoja de control se actualiza para el año específico (`ruta_planillas_anio`) de la iteración actual. Los mensajes de log (`logging.info`) antes y después de esta llamada lo demuestran.

2.  **Guardado independiente**: Al final de cada iteración del bucle anual, hay un bloque `try-except` que realiza el guardado:
    ```python
    try:
        control_sheet_path = os.path.join(ruta_informes_anio, CONTROL_SHEET_FILENAME)
        control_df.to_excel(control_sheet_path, index=False)
        logging.info(f"Hoja de control '{CONTROL_SHEET_FILENAME}' guardada para el año {anio.strip('/')}.")
    except Exception as e:
        logging.error(f"Error al guardar la hoja de control para el año {anio.strip('/')}: {e}")
    ```
    Aquí, `control_sheet_path` se construye utilizando `ruta_informes_anio`, lo que garantiza que la hoja de control se guarde en la carpeta de informes específica para cada año, y los `logging.info` confirman la acción de guardado anual.

## Procesamiento de Archivos Específico por Año y Tipo

### Subtask:
Confirmar que la función `procesar_archivo_excel` reciba la ruta del archivo completo y la configuración adecuada (ODS_CONFIG o XLSX_CONFIG) para cada archivo a procesar dentro del año actual de la iteración. Esto asegura que el procesamiento sea robusto y específico para el formato y la ubicación de cada archivo.

### Verificación de la función `procesar_archivo_excel`

Dentro de la celda `jWoNP2JxRlxf`, he localizado el bucle principal y la llamada a la función `procesar_archivo_excel`. Por favor, revisa el siguiente fragmento de código para confirmar los puntos especificados en la subtarea:

```python
            if os.path.isfile(ruta_archivo_completa):
                logging.info(f"Iniciando procesamiento del archivo: {nombre_archivo_con_ext} para el mes {mes_actual}")
                nombre_base, extension = os.path.splitext(nombre_archivo_con_ext)
                nombre_informe = f"informe de ventas {nombre_base}{extension}"
                ruta_salida_completa = os.path.join(ruta_informes_anio, nombre_informe)

                current_file_config = None
                if extension.lower() == '.ods':
                    current_file_config = ODS_CONFIG
                elif extension.lower() in ('.xlsx', '.xls'):
                    current_file_config = XLSX_CONFIG
                else:
                    logging.warning(f"Tipo de archivo desconocido para '{nombre_archivo_con_ext}'. Saltando este archivo.")
                    continue

                try:
                    # *** PUNTO DE VERIFICACIÓN ***
                    # 1. `ruta_archivo_completa` se pasa como el primer argumento.
                    # 2. `ruta_salida_completa` se pasa como el segundo argumento.
                    # 3. `current_file_config` se pasa como el tercer argumento (configuración adecuada según la extensión).
                    procesar_archivo_excel(ruta_archivo_completa, ruta_salida_completa, current_file_config)

                    control_df.loc[control_df['Mes'] == mes_actual, 'EstadoProcesamiento'] = STATUS_PROCESSED
                    control_df.loc[control_df['Mes'] == mes_actual, 'FechaUltimoProcesamiento'] = datetime.datetime.now()
                    logging.info(f"Archivo '{nombre_archivo_con_ext}' procesado exitosamente y estado actualizado a '{STATUS_PROCESSED}'.")
                except Exception as e:
                    logging.error(f"Error al procesar el archivo '{nombre_archivo_con_ext}': {e}. El estado no se ha actualizado a procesado.")
```

Como se puede observar, la función `procesar_archivo_excel` recibe `ruta_archivo_completa`, `ruta_salida_completa` y `current_file_config`, asegurando que el procesamiento sea específico para cada archivo y su formato.

## Final Task

### Subtask:
Resumir el trabajo completado y verificar que el programa puede procesar automáticamente las planillas de ventas para todos los años especificados en la variable ANIOS.

## Summary:

### Data Analysis Key Findings

*   **Dynamic Year Configuration**: The system processes years defined in the `ANIOS` variable. It requires a manual edit by the user to include all desired years in the format `['YYYY/']` (e.g., `ANIOS = ['2024/', '2025/']`). The current configuration was set to `['2026/']`.
*   **Dynamic Path Generation**: Paths for annual planning sheets (`ruta_planillas_anio`) and final reports (`ruta_informes_anio`) are correctly constructed dynamically within the main loop, ensuring proper directory targeting for each year.
*   **Automatic Report Folder Creation**: The system automatically verifies and creates year-specific report folders (`ruta_informes_anio`) if they do not exist, preventing `FileNotFoundError` and maintaining an organized structure.
*   **Year-Specific Control Sheet Management**: A unique control sheet (`_control.xlsx`) is loaded, created, updated, and saved independently for each year within its respective report folder. This allows for granular tracking of processing states for monthly files per year.
*   **File Type-Specific Processing**: The `procesar_archivo_excel` function correctly receives the full file path and the appropriate configuration (`ODS_CONFIG` or `XLSX_CONFIG`) based on the file's extension, ensuring robust and format-specific processing for each monthly sales file.

### Insights or Next Steps

*   The core processing logic for handling multiple years, dynamic paths, folder creation, control sheet management, and file-type specific processing is robustly implemented.
*   The user must manually update the `ANIOS` variable to specify all the years they wish to process, as this is the primary input for the system's annual iteration.
"""