# Generated by Django 4.0.6 on 2026-03-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportControlEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('drive_file_id', models.CharField(max_length=128, unique=True)),
                ('mime_type', models.CharField(blank=True, default='', max_length=128)),
                ('folder_id', models.CharField(blank=True, default='', max_length=128)),
                ('allowed', models.BooleanField(default=False)),
                ('processed', models.BooleanField(default=False)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('last_processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='reportcontrolentry',
            index=models.Index(fields=['folder_id'], name='reportes_re_folder__8a167b_idx'),
        ),
        migrations.AddIndex(
            model_name='reportcontrolentry',
            index=models.Index(fields=['allowed', 'processed'], name='reportes_re_allowed_0068de_idx'),
        ),
    ]
