# Generated by Django 4.0.6 on 2026-03-17 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bdd', '0001_initial'),
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklySalesSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('is_sin_registro', models.BooleanField(default=False)),
                ('cantidad_vendida', models.FloatField(default=0.0)),
                ('total_estimado', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bdd.item')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bdd.proveedor')),
            ],
        ),
        migrations.AddIndex(
            model_name='weeklysalessnapshot',
            index=models.Index(fields=['week_start', 'week_end'], name='reportes_we_week_st_f3f137_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklysalessnapshot',
            index=models.Index(fields=['proveedor'], name='reportes_we_proveed_c1932a_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklysalessnapshot',
            index=models.Index(fields=['item'], name='reportes_we_item_id_117f4c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='weeklysalessnapshot',
            unique_together={('week_start', 'week_end', 'proveedor', 'item', 'is_sin_registro')},
        ),
    ]
