# Generated by Django 4.0.6 on 2026-03-18 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bdd', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reportes', '0002_weeklysalessnapshot_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weeklysalessnapshot',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='weeklysalessnapshot',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='weeklysalessnapshot',
            name='vendedor_username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='weeklysalessnapshot',
            unique_together={('week_start', 'week_end', 'proveedor', 'item', 'vendedor', 'is_sin_registro')},
        ),
        migrations.AddIndex(
            model_name='weeklysalessnapshot',
            index=models.Index(fields=['vendedor'], name='reportes_we_vendedo_1858f2_idx'),
        ),
    ]
