# Generated by Django 4.0.6 on 2026-03-18 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bdd', '0001_initial'),
        ('reportes', '0003_alter_weeklysalessnapshot_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weeklysalessnapshot',
            unique_together={('week_start', 'week_end', 'proveedor', 'item', 'is_sin_registro')},
        ),
    ]
