# Generated by Django 4.0.6 on 2026-03-26 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0004_alter_weeklysalessnapshot_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeeklySalesSnapshot',
        ),
    ]
