"""
Django settings for core_config project.

Generated by 'django-admin startproject' using Django 4.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""


#Mercado Pago
#PAYMENT_HOST = 'https://localhost'
#PAYMENT_MODEL = 'viejo.Payment'

from ensurepip import bootstrap
from pathlib import Path
import os

os.environ['IP_BEW_SOCKET'] = 'ws://127.0.0.1:12000/ws'

#################
# para google ####################
#################

INBOX = '1JtiLUv_zYaYbGTAlUs_FHMNkzTs_cC5Y'
PLANTILLAS = '1G-TtSaGhLa5-d_PnIbLqnz59henhngwo'
DESCARGAR = '1MvOXlp1jhHZKgWaXpjmGphzBSyrj2a9F'

IP_BEW_SOCKET = "ws://127.0.0.1:12000/ws"


#######
# Rutas ####################
#######

#Url Base
ROOT_URLCONF = 'core_config.urls'
LOGIN_REDIRECT_URL = '/'

#Directorio Raiz
BASE_DIR = Path(__file__).resolve().parent.parent

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media_test')
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static_test')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]



###########
# Seguridad #################
###########


SECRET_KEY = 'django-insecure-5258*z#xf)z0f5bthv+xwa1v1n82(kmivxn1rd3l3ox6h8$s06'

INTERNET = True

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['darkydiel.pythonanywhere.com','localhost', '192.168.0.15', '192.168.1.104','192.168.1.119', '192.168.0.9','192.168.0.231','10.0.2.2','127.0.0.1']
ALLOWED_HOSTS = ['*']
IMPORT_EXPORT_USE_TRANSACTIONS = True
# Application definition


##############
# Aplicaciones ###############
##############

apps = [
    'core_docs',
    'core_andamios',
    'core_index',
    'core_elementos',
    'x_widgets',
    'x_articulos',
    'x_cartel',
    'bdd',
    'crispy_forms',
    'bootstrap4',
    'crispy_bootstrap4',
    'boletas',
    'carga_archivo',
    'facturacion',
    'cajas',
    'pedido',
    'articulos',
]

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.admindocs',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
]

INSTALLED_APPS += apps

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap4"

CRISPY_TEMPLATE_PACK = "bootstrap4"

STATICFILES_FINDERS = [
    # ...
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
    # ...
]

MIDDLEWARE = [
    'allauth.account.middleware.AccountMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

ACCOUNT_AUTHENTICATION_METHOD = "email"
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 7
ACCOUNT_LOGOUT_ON_GET = True

SITE_ID = 1

SOCIALACCOUNT_STORE_TOKENS = True

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
            'https://www.googleapis.com/auth/userinfo.email',
            'https://www.googleapis.com/auth/userinfo.profile',
            'https://www.googleapis.com/auth/drive',
            'https://www.googleapis.com/auth/drive.file',
            'https://www.googleapis.com/auth/gmail.readonly',
            'https://www.googleapis.com/auth/gmail.modify',
            'https://www.googleapis.com/auth/gmail.compose'
        ],
        'AUTH_PARAMS': {
            'access_type': 'offline',
        },
    }
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(STATIC_ROOT, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core_andamios.context_processors.mi_procesador_de_contexto',
            ],
        },
    },
]

WSGI_APPLICATION = 'core_config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': str(Path(__file__).resolve().parent / 'db_test.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'es-ar'

TIME_ZONE = 'America/Argentina/Buenos_Aires'

USE_I18N = True

USE_TZ = True



# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'