# Generated by Django 5.2.1 on 2025-07-05 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contenedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=30)),
                ('text_display', models.CharField(default='', max_length=30)),
                ('html', models.CharField(default='', max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contexto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', models.JSONField(default={})),
            ],
        ),
        migrations.CreateModel(
            name='Pie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=30)),
                ('text_display', models.CharField(default='', max_length=30)),
                ('html', models.CharField(default='', max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=30)),
                ('text_display', models.CharField(default='', max_length=30)),
                ('html', models.CharField(default='', max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=30)),
                ('text_display', models.CharField(default='', max_length=30)),
                ('ruta', models.CharField(default='', max_length=250)),
                ('contenedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_andamios.contenedor')),
                ('pie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_andamios.pie')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_andamios.script')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Nav_Bar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=30)),
                ('text_display', models.CharField(default='', max_length=30)),
                ('url', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core_andamios.url')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
