# Generated by Django 5.2.1 on 2025-07-05 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bdd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carteles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revisar', models.BooleanField(blank=True, default=False, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tamano_descripcion', models.IntegerField(default=100)),
                ('texto_final', models.TextField(blank=True, null=True)),
                ('tamano_texto_final', models.IntegerField(blank=True, null=True)),
                ('final', models.TextField(blank=True, null=True)),
                ('tamano_final', models.IntegerField(blank=True, null=True)),
                ('texto_final_efectivo', models.TextField(blank=True, null=True)),
                ('tamano_texto_final_efectivo', models.IntegerField(blank=True, null=True)),
                ('final_efectivo', models.TextField(blank=True, null=True)),
                ('tamano_final_efectivo', models.IntegerField(blank=True, null=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bdd.item')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bdd.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='CartelesCajon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revisar', models.BooleanField(blank=True, default=False, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tamano_descripcion', models.IntegerField(default=100)),
                ('texto_final', models.TextField(blank=True, null=True)),
                ('tamano_texto_final', models.IntegerField(blank=True, null=True)),
                ('final', models.TextField(blank=True, null=True)),
                ('tamano_final', models.IntegerField(blank=True, null=True)),
                ('texto_final_efectivo', models.TextField(blank=True, null=True)),
                ('tamano_texto_final_efectivo', models.IntegerField(blank=True, null=True)),
                ('final_efectivo', models.TextField(blank=True, null=True)),
                ('tamano_final_efectivo', models.IntegerField(blank=True, null=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bdd.item')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bdd.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Cartelitos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revisar', models.BooleanField(blank=True, default=False, null=True)),
                ('habilitado', models.BooleanField(blank=True, default=False, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bdd.item')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bdd.proveedor')),
            ],
        ),
    ]
