# Generated by Django 5.2.1 on 2025-07-05 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=1)),
                ('impreso', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comando',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comando', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenComando',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField()),
                ('boleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boletas.boleta')),
                ('comando', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boletas.comando')),
            ],
        ),
        migrations.AddField(
            model_name='boleta',
            name='comandos',
            field=models.ManyToManyField(through='boletas.OrdenComando', to='boletas.comando'),
        ),
    ]
