# Generated by Django 5.2.1 on 2025-07-05 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='nombre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('started_at', models.DateTimeField(verbose_name='iniciada el')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='finalizada el')),
                ('status', models.CharField(choices=[('running', 'En ejecución'), ('passed', 'Pasó'), ('failed', 'Falló'), ('error', 'Error')], default='running', max_length=10, verbose_name='estado')),
                ('duration', models.FloatField(blank=True, null=True, verbose_name='duración (segundos)')),
                ('total_tests', models.PositiveIntegerField(default=0, verbose_name='total de pruebas')),
                ('tests_passed', models.PositiveIntegerField(default=0, verbose_name='pruebas exitosas')),
                ('tests_failed', models.PositiveIntegerField(default=0, verbose_name='pruebas fallidas')),
                ('tests_error', models.PositiveIntegerField(default=0, verbose_name='errores')),
                ('tests_skipped', models.PositiveIntegerField(default=0, verbose_name='pruebas omitidas')),
                ('coverage_percent', models.FloatField(blank=True, null=True, verbose_name='cobertura de código (%)')),
                ('branch', models.CharField(blank=True, default='', max_length=100)),
                ('commit_hash', models.CharField(blank=True, default='', max_length=40)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ejecutado por')),
            ],
            options={
                'verbose_name': 'ejecución de pruebas',
                'verbose_name_plural': 'ejecuciones de pruebas',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodeid', models.CharField(max_length=1024, verbose_name='ID del nodo')),
                ('name', models.CharField(max_length=255, verbose_name='nombre')),
                ('file', models.CharField(max_length=512, verbose_name='archivo')),
                ('line', models.PositiveIntegerField(verbose_name='línea')),
                ('status', models.CharField(choices=[('passed', 'Pasó'), ('failed', 'Falló'), ('error', 'Error'), ('skipped', 'Omitido'), ('xfailed', 'Fallo esperado'), ('xpassed', 'Pasó inesperadamente')], max_length=10, verbose_name='estado')),
                ('duration', models.FloatField(verbose_name='duración (segundos)')),
                ('message', models.TextField(blank=True, verbose_name='mensaje')),
                ('traceback', models.TextField(blank=True, verbose_name='traza de error')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadatos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('test_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='core_testing.testrun', verbose_name='ejecución')),
            ],
            options={
                'verbose_name': 'caso de prueba',
                'verbose_name_plural': 'casos de prueba',
                'ordering': ['file', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ModuleCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(db_index=True, max_length=255, verbose_name='nombre del módulo')),
                ('coverage_percent', models.FloatField(verbose_name='porcentaje de cobertura')),
                ('lines_covered', models.PositiveIntegerField(verbose_name='líneas cubiertas')),
                ('lines_missing', models.PositiveIntegerField(verbose_name='líneas sin cubrir')),
                ('total_lines', models.PositiveIntegerField(verbose_name='total de líneas')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('file_coverage', models.JSONField(blank=True, default=dict, verbose_name='cobertura por archivo')),
                ('test_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module_coverages', to='core_testing.testrun', verbose_name='ejecución de pruebas')),
            ],
            options={
                'verbose_name': 'cobertura por módulo',
                'verbose_name_plural': 'cobertura por módulos',
                'ordering': ['module_name'],
            },
        ),
    ]
