# Generated by Django 5.2.1 on 2025-07-05 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo_Formularios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=30)),
                ('elemento_html', models.CharField(default='', max_length=30)),
                ('lista_de_campos', models.TextField(default='', max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Modelo_Listas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=30)),
                ('elemento_html', models.CharField(default='', max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Modelo_Tablas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=30)),
                ('elemento_html', models.CharField(default='', max_length=30)),
                ('lista_de_titulos', models.TextField(default='', max_length=300)),
                ('lista_articulos', models.TextField(default='', max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Modelo_Tarjetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=30)),
                ('elemento_html', models.CharField(default='', max_length=30)),
                ('titulo', models.CharField(default='', max_length=30)),
                ('descripcion', models.CharField(default='', max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Paginas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiene_tabla', models.BooleanField(default=False)),
                ('tiene_formulario', models.BooleanField(default=False)),
                ('tiene_tarjeta', models.BooleanField(default=False)),
                ('tiene_lista', models.BooleanField(default=False)),
                ('modelo_formularios', models.ManyToManyField(to='core_elementos.modelo_formularios')),
                ('modelo_lista', models.ManyToManyField(to='core_elementos.modelo_listas')),
                ('modelo_tablas', models.ManyToManyField(to='core_elementos.modelo_tablas')),
                ('modelo_tarjetas', models.ManyToManyField(to='core_elementos.modelo_tarjetas')),
            ],
        ),
    ]
