# Generated by Django 4.0.6 on 2026-03-26 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bdd', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CtaCteProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bdd.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('efectivo', 'Efectivo'), ('banco', 'Banco'), ('mp', 'MercadoPago'), ('tarjeta', 'Tarjeta de crédito')], max_length=16)),
                ('nombre', models.CharField(max_length=80)),
                ('banco', models.CharField(blank=True, max_length=80, null=True)),
                ('identificador', models.CharField(blank=True, max_length=120, null=True)),
                ('activa_desde', models.DateField(blank=True, null=True)),
                ('activa_hasta', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Impuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('sujeto_pasivo', models.CharField(max_length=120)),
                ('periodo', models.CharField(max_length=7)),
                ('ult_fecha', models.DateField(blank=True, null=True)),
                ('ult_monto', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('metodos_permitidos', models.JSONField(blank=True, default=list)),
                ('tipo', models.CharField(choices=[('nacional', 'Nacional'), ('provincial', 'Provincial'), ('municipal', 'Municipal')], max_length=12)),
                ('jurisdiccion', models.CharField(blank=True, max_length=120, null=True)),
                ('cuentas_permitidas', models.ManyToManyField(blank=True, to='administracion_financiera.cuenta')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('sujeto_pasivo', models.CharField(max_length=120)),
                ('periodo', models.CharField(max_length=7)),
                ('ult_fecha', models.DateField(blank=True, null=True)),
                ('ult_monto', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('metodos_permitidos', models.JSONField(blank=True, default=list)),
                ('identificador_contrato', models.CharField(blank=True, max_length=120, null=True)),
                ('cuentas_permitidas', models.ManyToManyField(blank=True, to='administracion_financiera.cuenta')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TicketDePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(blank=True, max_length=7, null=True)),
                ('vencimiento', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pagado', models.BooleanField(default=False)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('metodo_pago', models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('banco', 'Banco'), ('mp', 'MercadoPago'), ('tarjeta', 'Tarjeta de crédito')], max_length=16, null=True)),
                ('caduco', models.BooleanField(default=False)),
                ('semana_iso', models.CharField(blank=True, max_length=8, null=True)),
                ('cuenta_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='administracion_financiera.cuenta')),
                ('impuesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='administracion_financiera.impuesto')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='administracion_financiera.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='TarjetaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=80, null=True)),
                ('ult4', models.CharField(blank=True, max_length=4, null=True)),
                ('cierre_dia', models.PositiveSmallIntegerField()),
                ('vencimiento_dia', models.PositiveSmallIntegerField()),
                ('cuenta_liquidacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarjetas', to='administracion_financiera.cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateField()),
                ('medio_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('banco', 'Banco'), ('mp', 'MercadoPago'), ('tarjeta', 'Tarjeta de crédito')], max_length=16)),
                ('referencia', models.CharField(blank=True, max_length=120, null=True)),
                ('semana_iso', models.CharField(blank=True, max_length=8, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administracion_financiera.cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoCtaCte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('semana_iso', models.CharField(max_length=8)),
                ('object_id', models.PositiveIntegerField()),
                ('tipo', models.CharField(choices=[('cargo', 'Cargo'), ('abono', 'Abono')], max_length=8)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo_acumulado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('ctacte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='administracion_financiera.ctacteproveedor')),
            ],
        ),
        migrations.CreateModel(
            name='DebitoAutomatico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('cuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='administracion_financiera.cuenta')),
                ('impuesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion_financiera.impuesto')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion_financiera.servicio')),
                ('tarjeta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='administracion_financiera.tarjetacredito')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion_financiera.ticketdepago')),
            ],
        ),
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=40)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_emision', models.DateField()),
                ('fecha_diferido', models.DateField(blank=True, null=True)),
                ('fecha_cobro', models.DateField(blank=True, null=True)),
                ('banco', models.CharField(blank=True, max_length=80, null=True)),
                ('serie', models.CharField(blank=True, max_length=40, null=True)),
                ('plaza', models.CharField(blank=True, max_length=80, null=True)),
                ('estado', models.CharField(choices=[('emitido', 'Emitido'), ('cobrado', 'Cobrado'), ('devuelto', 'Devuelto'), ('salvado', 'Salvado')], default='emitido', max_length=10)),
                ('cuenta_emisora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administracion_financiera.cuenta')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bdd.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('numero', models.CharField(max_length=30)),
                ('punto_venta', models.CharField(max_length=8)),
                ('numero_completo', models.CharField(max_length=50)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pronto_pago_limite', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('vencida', 'Vencida'), ('caduco', 'Caduco')], default='pendiente', max_length=12)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('semana_iso', models.CharField(blank=True, max_length=8, null=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bdd.proveedor')),
            ],
        ),
        migrations.AddConstraint(
            model_name='debitoautomatico',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('servicio__isnull', False), ('impuesto__isnull', True), ('ticket__isnull', True)), models.Q(('servicio__isnull', True), ('impuesto__isnull', False), ('ticket__isnull', True)), models.Q(('servicio__isnull', True), ('impuesto__isnull', True), ('ticket__isnull', False)), _connector='OR'), name='debito_auto_objetivo_xor'),
        ),
        migrations.AddConstraint(
            model_name='debitoautomatico',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('cuenta__isnull', False), ('tarjeta__isnull', True)), models.Q(('cuenta__isnull', True), ('tarjeta__isnull', False)), _connector='OR'), name='debito_auto_cuenta_xor_tarjeta'),
        ),
        migrations.AddConstraint(
            model_name='boleta',
            constraint=models.UniqueConstraint(fields=('proveedor', 'punto_venta', 'numero_completo'), name='uniq_boleta_prov_pv_num'),
        ),
    ]
