# Generated by Django 4.0.6 on 2026-03-26 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bdd', '0001_initial'),
        ('administracion_financiera', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProveedorFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plazo_unidad', models.CharField(choices=[('dias', 'Días'), ('meses', 'Meses')], default='meses', max_length=10)),
                ('plazo_valor', models.PositiveIntegerField(default=1)),
                ('descuento_boleta_A', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('descuento_boleta_B', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('punto_venta', models.CharField(default='0001', max_length=8)),
                ('proveedor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financiero', to='bdd.proveedor')),
            ],
        ),
    ]
