# Generated by Django 5.2.1 on 2025-07-05 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bdd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticuloDevolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, null=True)),
                ('cantidad', models.FloatField(default=0.0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdd.item')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdd.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='ArticuloPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_created=True, default='2021-01-01')),
                ('cantidad', models.FloatField(default=0.0)),
                ('llego', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdd.item')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdd.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, null=True)),
                ('total', models.FloatField(default=0.0)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Pd', 'Pendiente'), ('En', 'Enviado'), ('Et', 'Entregado'), ('Co', 'Controlado')], default='Pd', max_length=20)),
                ('articulo_pedido', models.ManyToManyField(to='pedido.articulopedido')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdd.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Vendido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(default=0.0)),
                ('umbral', models.FloatField(default=0.0)),
                ('pedido', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdd.item')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdd.proveedor')),
            ],
        ),
    ]
